feat: support recent blocks, block details in sequencer tier
alleslabs/celatone-frontend pull request #1005
Opened 2024-07-04 11:47 UTC by evilpeach

Fixes: CFE-531, CFE-535

2024-07-05 03:46 UTC, Poafs1 commented on src/lib/services/tx/sequencer.ts
> +    .get(`${endpoint}/indexer/tx/v1/txs/by_height/${height}`, {
`encodeURI`

2024-07-05 03:53 UTC, Poafs1 submitted a review, later dismissed
look good

2024-07-05 07:48 UTC, songwongtp requested changes

2024-07-05 07:48 UTC, songwongtp commented on src/lib/pages/blocks/index.tsx
> +        lite={null}
make it optional like `sequencer`?

2024-07-05 07:48 UTC, songwongtp commented on src/lib/services/types/block.ts
> +      operator_address: zValidatorAddr.nullish(),
isn't this the same as validator_address? do we really need to have 2 fields for the same data?

2024-07-09 07:37 UTC, songwongtp approved these changes

2024-07-09 07:37 UTC, songwongtp commented on src/lib/services/types/block.ts
> +    height: Number(val.height),
Number => coerce

2024-07-09 09:03 UTC, merged

2024-07-09 09:13 UTC, Poafs1 reviewed
lgtm