feat(components): add apps menu to header
alleslabs/celatone-frontend pull request #1007
Opened 2024-07-05 08:09 UTC by jennieramida

## Describe your changes

## Demo Link

2024-07-10 06:06 UTC, Benzbeeb commented
LGTM

2024-07-17 09:23 UTC, evilpeach requested changes

2024-07-17 09:23 UTC, evilpeach commented on .github/workflows/jest.yml
> +      - uses: pnpm/action-setup@v4
please rebase or merge develop.

2024-07-17 09:23 UTC, evilpeach commented on src/lib/layout/AppMenu.tsx
> +                    {/* <CustomIcon
remove?

2024-07-17 09:23 UTC, evilpeach commented on src/lib/layout/AppMenu.tsx
> +              _hover={{
I think we should change cursor while hovering here.

2024-07-17 09:23 UTC, evilpeach commented on src/lib/layout/mobile/NavDrawer.tsx
> +        onClick={() => onOpen()}
onClick={onOpen}

2024-07-17 09:23 UTC, evilpeach commented on src/lib/layout/Header.tsx
> +export const SectionWrapper = ({
Create file for this component and don't forget to declare `SectionWrapperProps`

2024-07-17 11:09 UTC, evilpeach approved these changes
LGTM

2024-07-17 11:15 UTC, merged