[CFE-568]: Refactor(utils): home page overview, separate request
alleslabs/celatone-frontend pull request #1022
Opened 2024-07-15 08:48 UTC by Poafs1

2024-07-15 15:13 UTC, evilpeach commented on CHANGELOG.md
> +- [#1021](https://github.com/alleslabs/celatone-frontend/pull/1021) Add Milkyway network (glados-1)
Please rebase from develop branch

2024-07-15 16:05 UTC, songwongtp requested changes

2024-07-16 03:42 UTC, evilpeach commented on src/lib/services/stats/sequencer.ts
> +      avgBlockTimeLcd.status === "fulfilled" ? avgBlockTimeLcd.value : null,
Agree with it. It's no need to combine all together.

2024-07-16 07:19 UTC, evilpeach approved these changes

2024-07-16 07:27 UTC, songwongtp approved these changes

2024-07-16 07:27 UTC, songwongtp commented on src/lib/services/types/stats.ts
> +    blockTime: 0,
null

2024-07-16 07:27 UTC, songwongtp commented on src/lib/pages/home/full.tsx
> -            value={overviewsStats?.txCount.toLocaleString()}
toString

2024-07-16 07:27 UTC, songwongtp commented on src/lib/pages/home/sequencer.tsx
> -            value={overviewsStats?.txCount.toLocaleString()}
toString()

2024-07-16 09:03 UTC, merged