[CFE-585]: Feat(components): add local minitia to network selector
alleslabs/celatone-frontend pull request #1057
Opened 2024-07-31 14:56 UTC by Poafs1

2024-07-31 15:35 UTC, songwongtp requested changes

2024-07-31 15:35 UTC, songwongtp commented on src/lib/pages/add-network-manual/types.ts
>        layer: "2",
remove (otherwise there will be a subsection L2 in the custom section)

2024-07-31 15:38 UTC, songwongtp commented on src/lib/layout/network-menu/NetworkAccordion.tsx
>  export const NetworkAccordion = ({
I am thinking about creating a new component `NetworkAccordionLocal.tsx` which doesn't have the subsection components (I believe the design team says that there is no subsection for local)

2024-07-31 17:25 UTC, songwongtp commented on src/lib/layout/network-menu/NetworkMenuBody.tsx
add filteredLocalChains line 96 too

2024-08-01 04:39 UTC, evilpeach approved these changes

2024-08-01 04:40 UTC, songwongtp approved these changes

2024-08-01 04:47 UTC, merged