[CFE-553]: Feat(utils): move verify module api
alleslabs/celatone-frontend pull request #1081
Opened 2024-08-07 07:33 UTC by Poafs1

2024-08-08 11:12 UTC, songwongtp requested changes

2024-08-08 11:12 UTC, songwongtp commented on src/lib/services/types/verification/move/index.ts
> +export const zMoveVerifyInfosByModuleResponse = z.object({
ditto

2024-08-08 11:12 UTC, songwongtp commented on src/lib/services/types/verification/move/index.ts
> +export type MoveVerifyInfosByModuleResponse = z.infer<
ditto

2024-08-08 11:12 UTC, songwongtp commented on src/lib/services/verification/move/api.ts
> +export const getMoveVerifyInfosByModule = async (
ditto

2024-08-08 11:12 UTC, songwongtp commented on src/lib/services/verification/move/index.ts
> +export const useMoveVerifyInfosByModule = (
ditto

2024-08-09 10:03 UTC, songwongtp approved these changes

2024-08-09 11:10 UTC, evilpeach requested changes

2024-08-09 11:10 UTC, evilpeach commented on src/lib/services/verification/move/index.ts
> +  return useQuery(
Please use `useMutation`.

2024-08-09 11:10 UTC, evilpeach commented on src/lib/services/verification/move/index.ts
> +    () => getSubmitMoveVerify(formData),
Don't name get function because it's post function.

2024-08-09 15:50 UTC, evilpeach approved these changes

2024-08-09 16:20 UTC, merged