refactor: copy element
alleslabs/celatone-frontend pull request #206
Opened 2023-02-16 07:53 UTC by songwongtp

## Describe your changes
- Refactor copy functionality into one component

## Demo Link

2023-02-22 03:48 UTC, bkioshn approved these changes

2023-02-23 03:56 UTC, evilpeach requested changes

2023-02-23 03:56 UTC, evilpeach commented on src/lib/components/copy/CopyButton.tsx
> +  copyLabel = "Copied!",
It's no need to set default here. You've already set it on `CopyTemplate`

2023-02-23 03:56 UTC, evilpeach commented on src/lib/components/copy/Copier.tsx
> +  copyLabel = "Copied!",
ditto

2023-02-23 04:42 UTC, evilpeach approved these changes

2023-02-23 06:19 UTC, merged