fix: new design for token card
alleslabs/celatone-frontend pull request #210
Opened 2023-02-16 14:42 UTC by bkioshn

## Describe your changes
New design for token card

2023-02-20 04:00 UTC, poomthiti requested changes

2023-02-20 04:00 UTC, poomthiti commented on src/lib/pages/contract-details/components/token/TokenCard.tsx
> +        <Box>
just use div so you dont need to import Box

2023-02-20 04:48 UTC, bkioshn commented on src/lib/utils/formatter/price.ts
> +  return price.gte(1) ? price.toFixed(2) : price;
This is done according to the design. Might have to confirm with designer again.

2023-02-22 04:02 UTC, evilpeach approved these changes

2023-02-22 06:57 UTC, evilpeach approved these changes

2023-02-22 07:01 UTC, poomthiti approved these changes

2023-02-22 07:02 UTC, merged