feat: permission save new code
alleslabs/celatone-frontend pull request #214
Opened 2023-02-17 10:42 UTC by songwongtp

## Describe your changes
- Show code permission helper text in save new code modal
- 
## Demo Link

2023-02-22 05:54 UTC, bkioshn commented on src/lib/components/PermissionChip.tsx
> +export const getPermissionHelper = (
Should this be moved to util or somewhere else?

2023-02-23 12:14 UTC, evilpeach requested changes

2023-02-23 12:14 UTC, evilpeach commented on src/lib/components/PermissionChip.tsx
> +import { getPermissionHelper } from "lib/utils/codePermission";
'lib/utils'

2023-02-23 12:14 UTC, evilpeach commented on src/lib/components/modal/code/SaveNewCode.tsx
> +import { getPermissionHelper } from "lib/utils/codePermission";
ditto

2023-02-23 12:22 UTC, evilpeach approved these changes

2023-02-23 12:24 UTC, merged