feat: internal tx
alleslabs/celatone-frontend pull request #224
Opened 2023-02-24 04:04 UTC by songwongtp

## Describe your changes
- Support search by tx and internal tx link

## Demo Link

2023-02-24 04:08 UTC, poomthiti requested changes

2023-02-24 04:08 UTC, poomthiti commented on src/lib/components/modal/tx/ButtonSection.tsx
> +      `/${router.query.network}/tx/${txHash}`,
get network of current chain name instead

2023-02-24 05:05 UTC, poomthiti approved these changes

2023-03-01 08:50 UTC, evilpeach approved these changes

2023-03-01 09:01 UTC, merged