refactor: structure and components
alleslabs/celatone-frontend pull request #227
Opened 2023-02-27 18:37 UTC by songwongtp

## Describe your changes
- Refactor various components to reduce redundancy
- Reorganize components from a specific page to the general component directory if used multiple locations

## Demo Link

2023-02-28 07:22 UTC, traviolus approved these changes

2023-03-01 07:44 UTC, evilpeach requested changes

2023-03-01 07:44 UTC, evilpeach commented on src/lib/components/table/transactions/TransactionsTableRow.tsx
> +  const [isAccordion, setIsAccordion] = useState(false);
```suggestion
  const isAccordion = transaction.messages.length > 1;
```

2023-03-01 07:44 UTC, evilpeach commented on src/lib/model/contract.ts
> +export const useCodeContracts = (
useContractsByCodeId

2023-03-01 07:44 UTC, evilpeach commented on src/lib/pages/account-details/components/tables/AdminContractsTable.tsx
> +  const { contracts, isLoading } = useContractsAdmin(
useAccountAdminContracts

2023-03-01 07:44 UTC, evilpeach commented on src/lib/pages/account-details/components/tables/InstantiatedContractsTable.tsx
> +  const { contracts, isLoading } = useContractInstances(
useAccountContracts

2023-03-01 07:44 UTC, evilpeach commented on src/lib/pages/code-details/components/table/CodeContractsTable.tsx
> +        {totalData && totalData > 10 && (
!!totalData

2023-03-01 07:44 UTC, evilpeach commented on src/lib/pages/code-details/components/table/CodeContractsTable.tsx
> +    const tableHeaderId = "contractTableHeader";
use this on table header

2023-03-01 08:42 UTC, evilpeach approved these changes

2023-03-01 08:47 UTC, merged