feat: add faucet page
alleslabs/celatone-frontend pull request #228
Opened 2023-03-07 03:42 UTC by evilpeach

## Describe your changes
- add Faucet for requesting Testnet OSMO (Testnet only)

2023-03-07 06:20 UTC, bkioshn commented on src/lib/styles/theme/colors.ts
> +    background: "523600",
"#"

2023-03-07 06:20 UTC, bkioshn commented on src/lib/pages/faucet/index.tsx
> +      <TextInput
Should we add placeholder?

2023-03-07 06:20 UTC, bkioshn commented on src/lib/pages/faucet/index.tsx
> +        Testnet OSMO Faucet
OSMO Testnet Faucet

2023-03-07 10:57 UTC, bkioshn requested changes

2023-03-07 10:57 UTC, bkioshn commented on src/lib/components/button/FaucetButton.tsx
> +      <Text color="gray.600" fontWeight={700}>
should be text.dark

2023-03-07 10:57 UTC, bkioshn commented on src/lib/components/button/FaucetButton.tsx
> +      borderColor="gray.600"
pebble.600

2023-03-07 10:57 UTC, bkioshn commented on src/lib/pages/faucet/index.tsx
> +      <Text variant="body2" color="gray.100" pt={4} textAlign="center" mb={8}>
pebble.600

2023-03-08 18:33 UTC, evilpeach commented on src/lib/pages/faucet/index.tsx
> +        Testnet OSMO Faucet
Testnet OSMO Faucet is correct.

2023-03-08 18:51 UTC, evilpeach commented on src/lib/pages/faucet/index.tsx
> +      <TextInput
I'll discuss with designer.

2023-03-09 07:11 UTC, poomthiti requested changes

2023-03-09 07:11 UTC, poomthiti commented on src/lib/pages/faucet/index.tsx
> +        Testnet OSMO Faucet
todo: handle token symbol by chain

2023-03-09 07:11 UTC, poomthiti commented on src/lib/pages/faucet/index.tsx
> +        Receive 10.00 Testnet OSMO
osmo ditto

2023-03-09 07:37 UTC, poomthiti approved these changes

2023-03-09 07:37 UTC, bkioshn approved these changes

2023-03-09 07:44 UTC, merged