Feat/cw2 info
alleslabs/celatone-frontend pull request #230
Opened 2023-03-07 10:49 UTC by bkioshn

## Describe your changes
1. Add CW2 info column to code table including
- code list (my stored and my saved code)
- Recent code
- Public code
2. Code details
Note: if there is no info, will display "N/A" 
3. Remove unnecessary type in public project page

2023-03-10 09:45 UTC, evilpeach requested changes

2023-03-10 09:45 UTC, evilpeach commented on src/lib/pages/code-details/index.tsx
> +                {cw2Info || "N/A"}
`cw2Info ?? "N/A"`

2023-03-10 09:45 UTC, evilpeach commented on src/lib/pages/codes/components/CodesTable.tsx
> +          {cw2Info || "N/A"}
ditto

2023-03-10 09:45 UTC, evilpeach commented on src/lib/pages/contract-details/components/tables/migration/MigrationRow.tsx
> +          {cw2Info || "N/A"}
ditto

2023-03-10 09:45 UTC, evilpeach commented on src/lib/pages/contract-details/components/tables/migration/index.tsx
> +    <TableContainer>
Will it break the old interface?

2023-03-10 09:45 UTC, evilpeach commented on src/lib/pages/public-project/components/table/code/PublicProjectCodeRow.tsx
> +  const { publicInfo } = publicCodeInfo;
On line 20, you can destructure as follows.
```tsx
publicCodeInfo: { publicInfo },
```
and remove line 25

2023-03-10 09:45 UTC, evilpeach commented on src/lib/pages/public-project/components/table/code/PublicProjectCodeRow.tsx
> +          {cw2Info || "N/A"}
use `??`

2023-03-10 10:52 UTC, bkioshn commented on src/lib/pages/contract-details/components/tables/migration/index.tsx
> +    <TableContainer>
Nope

2023-03-11 17:28 UTC, evilpeach approved these changes
lgtm

2023-03-13 03:22 UTC, merged