Fix/css related issue
alleslabs/celatone-frontend pull request #235
Opened 2023-03-09 11:03 UTC by jennieramida

## Describe your changes

## Demo Link

2023-03-09 12:37 UTC, songwongtp requested changes

2023-03-09 12:37 UTC, songwongtp commented on src/lib/components/forms/TextInput.tsx
> +        helperText && (
Might have a problem if we only have status but no helpertext

2023-03-10 04:47 UTC, poomthiti requested changes

2023-03-10 04:47 UTC, poomthiti commented on src/lib/pages/query/components/QueryArea.tsx
> +          <Text variant="body3" mb="2">
I prefer to write mb={2} to differentiate between arbitrary unit ("8px") and chakra space format (2)

2023-03-10 04:47 UTC, poomthiti commented on src/lib/pages/query/components/QueryArea.tsx
> +            rowGap="2"
ditto

2023-03-10 04:47 UTC, poomthiti commented on src/lib/layout/navbar/index.tsx
> +        }
add comment for each case e.g. Handle path params, Handle query params

2023-03-10 04:47 UTC, poomthiti commented on src/lib/layout/navbar/index.tsx
> +            return pathName === `/${network}${slug}`;
```tsx
case "/contract-list":
case "/public-project":
   return pathName === `/${network}${slug}`;
```

2023-03-10 04:51 UTC, poomthiti commented
Change handleOnClick in PublicProjectCard to this
```ts
const handleOnClick = () => {
      navigate({ pathname: `/public-project/[slug]`, query: { slug } });
    };
```

2023-03-10 04:52 UTC, evilpeach commented on src/lib/layout/navbar/index.tsx
>    const isCurrentPage = useCallback(
```tsx
  const isCurrentPage = useCallback(
    (slug: string) => {
      const networkPath = network ? `/${network}` : "";

      switch (slug) {
        // handle home page
        case "/":
          return pathName === `${networkPath}`;
        // handle contract list page and public project page
        case "/contract-list":
        case "/public-project":
          return pathName === `${networkPath}${slug}`;
        // handle page with query param
        default:
          return pathName.includes(`${networkPath}${slug}`);
      }
    },
    [network, pathName]
  );
```

2023-03-11 17:24 UTC, evilpeach approved these changes
lgtm

2023-03-11 17:25 UTC, merged