feat: table drawers
alleslabs/celatone-frontend pull request #240
Opened 2023-03-14 08:08 UTC by songwongtp

## Describe your changes
- table drawer for contract selection - query/execute and migrate
- for code selection - deploy, migrate, and update admin

## Demo Link

2023-03-14 10:59 UTC, bkioshn requested changes
- add `ml="1px"` to `CustomIcon` in `EditableCell`
- Implement disable list when list contains 0 contracts

2023-03-15 07:02 UTC, songwongtp commented
> * add `ml="1px"` to `CustomIcon` in `EditableCell`
> * Implement disable list when list contains 0 contracts

fixed

2023-03-16 04:37 UTC, bkioshn commented on src/lib/components/select-contract/ContractListCard.tsx
>    const showLastUpdated = item.slug !== formatSlugName(INSTANTIATED_LIST_NAME);
Change name to avoid confusion -> isInstantiateList

2023-03-17 14:21 UTC, evilpeach requested changes

2023-03-17 14:21 UTC, evilpeach commented on src/lib/styles/theme/components/drawer.ts
> +    transition: "all 0s",
remove

2023-03-17 14:21 UTC, evilpeach commented on CHANGELOG.md
> +- [#240](https://github.com/alleslabs/celatone-frontend/pull/240) Change modals containing tables to drawers for easier exploration
this branch should be updated follow the most recent commit on the 'develop' branch

2023-03-20 02:43 UTC, bkioshn approved these changes

2023-03-20 03:40 UTC, evilpeach approved these changes
lgtm

2023-03-20 03:40 UTC, merged