fix: natoken size
alleslabs/celatone-frontend pull request #241
Opened 2023-03-15 05:54 UTC by bkioshn

## Describe your changes
Fix NAToken component size

2023-03-16 04:27 UTC, poomthiti approved these changes

2023-03-16 04:30 UTC, poomthiti commented
In TokenCard component: If h="101px" is there in order to set the minimum height of the card, use minH instead so the component can flex responsively

2023-03-16 07:06 UTC, poomthiti approved these changes

2023-03-17 03:13 UTC, songwongtp approved these changes

2023-03-17 04:44 UTC, evilpeach requested changes
Please update branch to latest commit

2023-03-17 04:57 UTC, evilpeach approved these changes

2023-03-17 05:02 UTC, merged