feat: add table for proposal list page
alleslabs/celatone-frontend pull request #260
Opened 2023-03-30 06:17 UTC by bkioshn

## Describe your changes
Add proposal list table to proposal list page

2023-04-03 07:28 UTC, poomthiti requested changes

2023-04-03 07:28 UTC, poomthiti commented on src/lib/pages/proposals/table/ProposalTableRow.tsx
> +  const hoverBg = () => {
specify return type

2023-04-03 07:46 UTC, bkioshn commented on src/lib/pages/proposals/index.tsx
> +    undefined
Will implement this later in another PR

2023-04-04 10:40 UTC, evilpeach commented on src/lib/pages/proposals/table/ProposalTableRow.tsx
> +  const isInactive = proposal.status === ProposalStatus.INACTIVE;
Let's use `isActive`

2023-04-04 10:40 UTC, evilpeach commented on src/lib/pages/proposals/table/ProposalTableRow.tsx
> +  const columnsWidth = templateColumns?.toString().split(" ");
add todo

2023-04-04 10:40 UTC, evilpeach commented on src/lib/pages/proposals/table/ProposalTableRow.tsx
> +        !isInactive ??
isActive || ...

2023-04-04 10:58 UTC, merged