feat: new Txs Tables
alleslabs/celatone-frontend pull request #261
Opened 2023-04-04 08:06 UTC by songwongtp

## Describe your changes
- Add relation column
- Add block height column
- Add relation filter
- Refactor txs table

## Demo Link

2023-04-09 16:46 UTC, evilpeach requested changes

2023-04-09 16:46 UTC, evilpeach commented on src/lib/services/txService.ts
> +} from "lib/gql/graphql";
We shouldn't import from `lib/gql/graphql`

2023-04-09 16:46 UTC, evilpeach commented on src/lib/services/txService.ts
> +  relation: Option<boolean>,
isRelated?

2023-04-09 16:46 UTC, evilpeach commented on src/lib/services/txService.ts
>           */
remove

2023-04-09 16:46 UTC, evilpeach commented on src/lib/services/txService.ts
>              /* these value must not be null */
remove

2023-04-09 16:46 UTC, evilpeach commented on src/lib/services/txService.ts
> +        account_transactions.map((tx) => ({
Turn `tx` to `{transaction}`.

2023-04-09 16:46 UTC, evilpeach commented on src/lib/pages/past-txs/types.ts
> +  relation: Option<boolean>;
isRelated or isSigner?

2023-04-10 05:43 UTC, bkioshn requested changes

2023-04-10 05:43 UTC, bkioshn commented on src/lib/components/table/transactions/TransactionsTableRow.tsx
> +        {showAction && (
in 
```
<AccordionTx
    key={index.toString() + msg.type}
    message={msg}
    allowFurtherAction={false}
/>
))}
```
change `allowFurtherAction={false}` to `allowFurtherAction={showAction}`

2023-04-10 11:36 UTC, evilpeach approved these changes

2023-04-10 11:54 UTC, bkioshn approved these changes

2023-04-10 15:41 UTC, merged