feat: add instantiate permission to store code message
alleslabs/celatone-frontend pull request #279
Opened 2023-04-17 09:29 UTC by bkioshn

## Describe your changes
- Add instantiate permission to msg store code.
- Upgrade cosmjs to version 0.30.1 to support instantiate permission any of address

2023-04-26 06:50 UTC, evilpeach requested changes

2023-04-26 06:50 UTC, evilpeach commented on src/lib/components/upload/InstantiatePermissionRadio.tsx
> +                <AddressPermissionInput
add key

2023-04-26 10:03 UTC, songwongtp requested changes

2023-04-26 10:08 UTC, evilpeach commented on src/lib/app-fns/tx/upload.tsx
> +      const codeId = findAttr(mimicLog, "store_code", "code_id") || "0";
use `||` instead of `??`

2023-04-26 10:08 UTC, evilpeach commented on src/lib/app-provider/queries/simulateFee.ts
> +  addresses: Record<"address", Addr>[];
Let's pass `address[]` instead.

2023-04-26 10:16 UTC, evilpeach commented on src/lib/components/upload/UploadSection.tsx
> +    (!addresses.some((addr) => addr.address !== "") || isAddressesError);
We should merge `isAddressesError` and `isAnyAddrWithoutInput`, and change `addr.address !== ""` to `addr.address.trim().length !== 0`

2023-04-27 04:12 UTC, evilpeach commented on src/lib/components/upload/UploadSection.tsx
>      (async () => {
remove async

2023-04-27 04:21 UTC, evilpeach approved these changes

2023-04-27 08:23 UTC, evilpeach commented on src/lib/components/upload/UploadSection.tsx
> +      // TODO - Remove this later
remove this comment.

2023-04-27 08:23 UTC, evilpeach commented on src/lib/components/upload/UploadSection.tsx
>      postUploadTx,
I think we should add `JSON.stringify(addresses)` as well

2023-04-27 09:47 UTC, merged