feat(components): add public account to public project
alleslabs/celatone-frontend pull request #289
Opened 2023-04-20 08:51 UTC by jennieramida

## Describe your changes

## Demo Link

2023-04-20 09:56 UTC, songwongtp requested changes

2023-05-02 07:28 UTC, poomthiti requested changes

2023-05-02 07:28 UTC, poomthiti commented on src/lib/pages/public-project/components/table/account/PublicProjectAccountRow.tsx
> +    });
create util fn on top of this const
```tsx
const getNavigationArgs = (accountInfo: Account): NavigationArgs => {
switch (accountInfo.type) {
  case "account": 
    return {
      pathname: "/account/[accountAddress]",
      query: {accountAddress: accountInfo.address}
    }
  case "contract": ..........
}
}
```

2023-05-02 09:37 UTC, bkioshn requested changes

2023-05-02 09:37 UTC, bkioshn commented on src/lib/pages/public-project/components/table/account/PublicProjectAccountTable.tsx
> +  return (
Should we add empty state when search not found? use `!filteredAccounts.length`

2023-05-02 10:17 UTC, evilpeach approved these changes

2023-05-02 10:18 UTC, bkioshn approved these changes

2023-05-02 10:19 UTC, poomthiti approved these changes

2023-05-02 10:23 UTC, songwongtp approved these changes

2023-05-02 10:24 UTC, merged