Feat/pool tx table
alleslabs/celatone-frontend pull request #294
Opened 2023-04-23 17:24 UTC by songwongtp

## Describe your changes
- Add Pool related txs table with blank states

## Demo Link

2023-05-03 06:00 UTC, bkioshn commented on src/lib/pages/pool/components/table/pool-txs/messages/swap/MsgSwapExactAmountInAction.tsx
> +          {getTokenLabel(outAssetInfo?.symbol || tokenOutDenom)}
ditto

2023-05-03 07:16 UTC, bkioshn commented on src/lib/pages/pool/components/PoolRelatedTxs.tsx
>        <Flex mt={12} gap={2} alignItems="center">
create `const tableHeaderId = "poolTableHeader"` and add `id={tableHeaderId}` to heading, and pass it to `PoolRelatedTxsTable` for pagination scroll

2023-05-03 08:15 UTC, songwongtp commented on src/lib/pages/pool/components/table/pool-txs/messages/swap/MsgSwapExactAmountOutDetail.tsx
> +  return (
Information in the messages are not the same

2023-05-03 10:47 UTC, poomthiti requested changes

2023-05-03 10:47 UTC, poomthiti commented on src/lib/pages/pools/components/table/pool-txs/messages/swap/MsgSwapExactAmountInAction.tsx
> +            <CustomIcon name="info-circle" boxSize="3" />
number boxSize

2023-05-03 10:47 UTC, poomthiti commented on src/lib/pages/pools/components/table/pool-txs/messages/swap/MsgSwapExactAmountOutAction.tsx
> +            <CustomIcon name="info-circle" boxSize="3" />
boxSize number

2023-05-03 10:47 UTC, poomthiti commented on src/lib/pages/pools/components/table/pool-txs/messages/swap/PoolRoute.tsx
> +            key={pool.poolId}
might duplicate with other transactions

2023-05-03 10:47 UTC, poomthiti commented on src/lib/pages/pools/components/table/pool-txs/messages/swap/PoolSwap.tsx
> +
add remark

2023-05-03 10:47 UTC, poomthiti commented on src/lib/pages/pools/components/table/pool-txs/messages/swap/PoolSwap.tsx
> +      <Box>
replace Box with div

2023-05-09 07:20 UTC, songwongtp commented on src/lib/pages/pool/components/PoolRelatedTxs.tsx
> +  poolId: number;
this is already checked from its parent file `poolId.tsx`

2023-05-09 07:26 UTC, songwongtp commented on src/lib/pages/pool/components/table/pool-txs/PoolTxsTableRow.tsx
> +    .join(" ");
this will be complicated outside instead, so doesn't matter

2023-05-09 07:28 UTC, songwongtp commented on src/lib/pages/pool/components/table/pool-txs/PoolTxsTableRow.tsx
> +    >
need to cover the expanded section too which is another grid, so Box is needed

2023-05-09 07:47 UTC, songwongtp commented on src/lib/pages/pool/components/table/pool-txs/PoolTxsTableRow.tsx
> +              assetInfos={assetInfos}
too many unneeded info for me

2023-05-23 07:39 UTC, evilpeach requested changes
Replace all `PoolDetail<Big, TokenWithValue>` with `PoolDetail`

2023-05-23 08:10 UTC, poomthiti commented on src/lib/pages/pools/components/PoolHeader.tsx
> +type PoolHeaderProps = Pick<PoolDetail, "isSuperfluid" | "poolLiquidity"> & {
I prefer interface extension for better readability

2023-05-23 08:39 UTC, evilpeach requested changes

2023-05-23 08:39 UTC, evilpeach commented on src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/utils.ts
> +};
You can use `parseCoins` util function and get first index.

2023-05-23 09:29 UTC, poomthiti requested changes

2023-05-23 09:29 UTC, poomthiti commented on src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/lp/components/PoolAssetsGrid.tsx
> +    ?.events?.find((event) => event.type === "coin_received");
findAttr

2023-05-23 09:29 UTC, poomthiti commented on src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/lp/components/PoolLPCard.tsx
> +    ?.events?.find((event) => event.type === "coin_received")
findAttr

2023-05-23 09:29 UTC, poomthiti commented on src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/lp/components/PoolLPCard.tsx
> +        assetText={isJoin ? "Received " : "Burn "}
space

2023-05-23 09:29 UTC, poomthiti commented on src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/swap/components/PoolSwap.tsx
> +    ?.events?.find((event) => event.type === "token_swapped");
findAttr

2023-05-23 09:51 UTC, songwongtp commented on src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/lockup/MsgLockTokensDetail.tsx
> +        event.type.includes("lock") &&
can't since event names can be different due to two situations

2023-05-23 09:54 UTC, evilpeach approved these changes

2023-05-23 10:29 UTC, merged