feat: show deposit/voting period from gov params and add alert
alleslabs/celatone-frontend pull request #298
Opened 2023-04-25 11:14 UTC by poomthiti

Show deposit/voting period from gov params and add minimum required alert

## Describe your changes

## Demo Link

2023-05-02 08:48 UTC, bkioshn approved these changes

2023-05-03 09:37 UTC, evilpeach requested changes

2023-05-03 09:37 UTC, evilpeach commented on src/lib/services/delegation.ts
> +    unbondingTime: formatSeconds(data.params.unbonding_time.slice(0, -1)),
remove `slice`

2023-05-09 07:04 UTC, evilpeach requested changes

2023-05-09 07:04 UTC, evilpeach commented on src/lib/services/proposal.ts
> +}
Let's use `SnakeToCamelCase` type condition and use snake case for raw data from lcd and camel case for internal use

Ref. https://www.typescriptlang.org/play?#code/C4TwDgpgBAygdgQwNYQCoHsDCCC2EA22AzhADwxQQAewEcAJkVEcAE4CWcA5gHxQC8sSjTqMoAAwAkAb04AzCKyioAvgH0Z8xVACqK8QCgoUAPwSZqmdjDtgCfOwBeZeMjRZcBYmR08e+oygALlgAbgMDUEgoKgFYRBQMbDxCBBJSAHIcTjVOW3Z7NXoIMHQiWzUAJgyeCMjwaFdEjxTvADkIFgh6UlQ+QVRhWgYmdAAjACsIAGNgQLNpQONjAG0AaShOKBQQdDllKDT4tyTPVPSNgDJmNk5eAF0QpvdkrzSIDq6epeXjVHX7j9jDxwr8VIEQqhwgZOLRWHIENNoAAlBAAdwAIiUyrYAAoIVi4JiLAD0JOW2TgRWx5WAITgAFccGNFCt7qCoDgEFRqaVaWpIBx0PQQiwONxwmSKTlqJB6LZurycXSoIzmaz2YFKbk4PlCsU+RVCcB2OhRbcJYFSugcGo5OxWCwQotfvbHcA1GN8OhhebxVwOcZ6OgGV6IGokOx8PhnUDlsHKQgTegqXgEFSEAA3LghMY+-AQdOB35QLjChwoNRw22R6OxksN7ZpehqNITegTJCtogdhD0pks1hx4zgsGBcHg+rRLGG4D4wk4JiCZ6nVrvT60HqozE0vEEom1IA

2023-05-09 07:04 UTC, evilpeach commented on src/lib/services/proposalService.ts
> +  initialDeposit: Token;
let's rename to `minInitialDeposit`

2023-05-09 09:22 UTC, evilpeach commented on src/lib/services/proposal.ts
> +import type { SnakeToCamelCaseNested } from "lib/types/converter";
This type should be imported from `lib/types`

2023-05-09 09:25 UTC, evilpeach commented on src/lib/services/proposal.ts
> +    .get(`${lcdEndpoint}/cosmos/gov/v1beta1/params/voting`)
`get<{voting_params: VotingParams}>`

2023-05-09 10:23 UTC, evilpeach approved these changes
lgtm

2023-05-09 10:24 UTC, merged