fix(components): refine button and spinner
alleslabs/celatone-frontend pull request #311
Opened 2023-05-02 10:04 UTC by jennieramida

## Describe your changes

## Demo Link

2023-05-10 05:57 UTC, bkioshn commented on src/lib/pages/codes/index.tsx
> +      >
remove color

2023-05-10 05:57 UTC, bkioshn commented on CHANGELOG.md
> +- [#311](https://github.com/alleslabs/celatone-frontend/pull/311) Refine css styling
Merge develop for changelog update

2023-05-10 05:57 UTC, bkioshn commented on src/lib/styles/theme/components/tag.ts
> +    violetLight,
others variants are using kebab case eg. "outlint-primary" might consider changing this

2023-05-11 04:31 UTC, songwongtp requested changes

2023-05-11 04:31 UTC, songwongtp commented on src/lib/components/table/contracts/TagsCell.tsx
> +                return <Tag key={item}>{item}</Tag>;
`tags.map((item) => (<Tag key={item}>{item}</Tag>))`

2023-05-12 08:08 UTC, evilpeach commented on src/lib/pages/proposals/index.tsx
> +import { Tooltip } from "lib/components/TooltipComponent";
I'd rather call it 'Tooltip' than 'TooptipComponent'.

2023-05-12 08:46 UTC, evilpeach commented on src/lib/components/table/EditableCell.tsx
> +              <Tooltip hasArrow label={tooltip}>
remove `hasArrow`

2023-05-12 08:51 UTC, evilpeach commented on src/lib/components/button/InstantiateButton.tsx
> +    <Tooltip hasArrow label={tooltipLabel}>
remove `hasArrow` ?

2023-05-12 09:00 UTC, evilpeach approved these changes

2023-05-12 09:43 UTC, merged