fix: change app context and related comps
alleslabs/celatone-frontend pull request #315
Opened 2023-05-03 07:15 UTC by songwongtp

## Describe your changes
- change app context and related comps

## Demo Link

2023-05-12 09:05 UTC, poomthiti requested changes

2023-05-12 09:05 UTC, poomthiti commented on src/lib/app-provider/hooks/useInternalNavigate.ts
> +  const defaultChainId = SUPPORTED_CHAIN_IDS[0] ?? "";
ditto

2023-05-14 14:17 UTC, evilpeach commented on src/env.ts
>  export const FALLBACK_LCD_ENDPOINT: Record<string, string> = {
We'll remove it in the upcoming PR.

2023-05-14 14:36 UTC, evilpeach commented on src/lib/app-provider/hooks/useCelatoneApp.ts
> +  return useApp();
Agreed!

2023-05-15 04:29 UTC, poomthiti requested changes

2023-05-15 04:29 UTC, poomthiti commented on src/pages/_app.tsx
> -          endpointOptions={availableChainsEndpoints}
if we remove this, the wallet will use keplr rpc for sending transaction not from config

2023-05-15 06:14 UTC, poomthiti approved these changes

2023-05-15 06:15 UTC, evilpeach approved these changes

2023-05-15 06:16 UTC, merged