feat: add amplitude to proposal to store code page
alleslabs/celatone-frontend pull request #321
Opened 2023-05-10 03:06 UTC by bkioshn

## Describe your changes
Add amplitude to proposal to sore code page

2023-05-10 07:13 UTC, songwongtp approved these changes

2023-05-10 08:46 UTC, poomthiti requested changes

2023-05-10 08:46 UTC, poomthiti commented on src/lib/services/amplitude.tsx
> +    type: AccessType[type],
just pass in type

2023-05-10 08:46 UTC, poomthiti commented on src/lib/services/amplitude.tsx
> +    big(initialDeposit) < big(minDeposit || "0") ? "Deposit" : "Voting";
big(initialDeposit).lt(minDeposit || "0")

2023-05-10 08:46 UTC, poomthiti commented on src/lib/services/amplitude.tsx
> +  properties?: Dict<string, any>
just merge to only one arg and define interface something like this
```
{
  properties: {
    initialDeposit: string,
    minDeposit: Option<string>,
   [key:string]: any
  }
}
```

2023-05-10 08:46 UTC, poomthiti commented on src/lib/pages/proposal/store-code/index.tsx
> +      }
merge to only one obj

2023-05-10 08:46 UTC, poomthiti commented on src/lib/pages/proposal/store-code/index.tsx
> +  const page = "proposal-store-code";
define outside of component

2023-05-10 08:46 UTC, poomthiti commented on src/lib/components/upload/InstantiatePermissionRadio.tsx
> +  }, [addresses, append, page, permission, remove]);
remove append and remove

2023-05-10 08:46 UTC, poomthiti commented on src/lib/pages/proposal/constants.tsx
> +            AmpTrackUseRightHelperPanel(storeCodePage, "to-/deploy")
to-deploy?

2023-05-11 04:29 UTC, evilpeach approved these changes

2023-05-11 04:30 UTC, poomthiti approved these changes

2023-05-11 04:30 UTC, merged