feat: add tab url path for account details and public project details
alleslabs/celatone-frontend pull request #322
Opened 2023-05-10 04:40 UTC by poomthiti

## Describe your changes

## Demo Link

2023-05-10 08:04 UTC, songwongtp approved these changes

2023-05-23 04:15 UTC, bkioshn approved these changes

2023-05-23 11:09 UTC, evilpeach requested changes
fix route to plural form

2023-07-20 08:36 UTC, evilpeach requested changes

2023-07-20 08:36 UTC, evilpeach commented on src/lib/pages/public-project/slug.tsx
> +  const tab = getFirstQueryParam(router.query.tab) as TabIndex;
add `//TODO: remove assertion later`

2023-07-20 08:36 UTC, evilpeach commented on src/lib/pages/account-details/index.tsx
> +  const tab = getFirstQueryParam(router.query.tab) as TabIndex;
ditto

2023-07-20 10:28 UTC, evilpeach approved these changes

2023-07-20 10:28 UTC, merged