Feat/breadcrumb
alleslabs/celatone-frontend pull request #323
Opened 2023-05-10 07:05 UTC by jennieramida

## Describe your changes

## Demo Link

2023-05-10 07:24 UTC, songwongtp requested changes

2023-05-10 07:24 UTC, songwongtp commented on src/lib/components/DefaultBreadcrumb.tsx
> +export const DefualtBreadcrumb = ({
*Default

2023-05-10 07:24 UTC, songwongtp commented on src/lib/pages/block-details/components/BlockDetailsTop.tsx
> +          </Flex>{" "}
remove {" "}

2023-05-11 04:37 UTC, songwongtp requested changes

2023-05-11 04:37 UTC, songwongtp commented on src/lib/components/DefaultBreadcrumb.tsx
> +    separator={<CustomIcon name="chevron-right" boxSize="3" />}
boxSize={3}

2023-05-11 04:37 UTC, songwongtp commented on src/lib/components/DefaultBreadcrumb.tsx
> +  mb?: string;
change to number

2023-05-11 04:37 UTC, songwongtp commented on src/lib/pages/contract-details/components/ContractTop.tsx
> +            mb="24px"
mb={6}

2023-05-11 04:37 UTC, songwongtp commented on src/lib/pages/account-details/index.tsx
> +            mb="24px"
mb={6}

2023-05-16 17:25 UTC, evilpeach requested changes

2023-05-29 18:50 UTC, poomthiti requested changes

2023-05-29 18:50 UTC, poomthiti commented on src/lib/pages/account-details/index.tsx
> +            <CustomIcon name="wallet" boxSize="5" color="secondary.main" />
{5}

2023-05-29 18:50 UTC, poomthiti commented on src/lib/pages/block-details/components/BlockDetailsTop.tsx
> +            <CustomIcon name="block" boxSize="5" color="secondary.main" />
{5}

2023-05-29 18:50 UTC, poomthiti commented on src/lib/pages/block-details/index.tsx
> +          { text: blockData?.height.toString() ?? "" },
remove ??

2023-05-29 18:50 UTC, poomthiti commented on src/lib/pages/code-details/index.tsx
> +        <Flex direction="column">
remove, not necessary

2023-05-29 18:50 UTC, poomthiti commented on src/lib/pages/code-details/index.tsx
> +                text: publicProject.publicDetail?.name ?? null,
remove ??

2023-05-29 18:50 UTC, poomthiti commented on src/lib/pages/code-details/index.tsx
> +              { text: codeId.toString() ?? "" },
remove ??

2023-05-29 18:50 UTC, poomthiti commented on src/lib/pages/public-project/components/DetailHeader.tsx
> +        { text: details?.name ?? "" },
remove ??

2023-05-30 07:09 UTC, poomthiti requested changes

2023-05-30 07:09 UTC, poomthiti commented on src/lib/pages/code-details/index.tsx
> +              href: publicProject.publicCodeData?.name ? `/projects` : "/codes",
"/projects"

2023-05-30 07:17 UTC, poomthiti approved these changes

2023-05-30 07:17 UTC, songwongtp approved these changes

2023-05-30 07:37 UTC, evilpeach approved these changes

2023-05-30 07:38 UTC, merged