feat: add amplitude tracking for whitelist page
alleslabs/celatone-frontend pull request #326
Opened 2023-05-11 07:27 UTC by poomthiti

## Describe your changes

## Demo Link

2023-05-16 03:48 UTC, bkioshn approved these changes

2023-05-16 06:19 UTC, evilpeach requested changes

2023-05-16 06:19 UTC, evilpeach commented on src/lib/pages/proposal/whitelist/index.tsx
> +                    onClick={() => {
remove brackets

2023-05-16 06:19 UTC, evilpeach commented on src/lib/pages/proposal/whitelist/index.tsx
> +                onClick={() => {
ditto

2023-05-17 06:23 UTC, evilpeach approved these changes

2023-05-17 06:23 UTC, merged