feat: implement flow for store code allowed user
alleslabs/celatone-frontend pull request #329
Opened 2023-05-11 10:41 UTC by bkioshn

## Describe your changes
Implement flow for store code allowed user

2023-05-15 04:34 UTC, poomthiti requested changes

2023-05-15 04:34 UTC, poomthiti commented on src/lib/pages/codes/components/MyStoredCodesSection.tsx
> +          )}
is this logic only valid for osmosis?

2023-05-15 04:34 UTC, poomthiti commented on src/lib/pages/codes/components/UploadButton.tsx
> +  );
receive as props, general small component shouldn't be the one to fetch data

2023-05-15 04:34 UTC, poomthiti commented on src/lib/pages/upload/index.tsx
> +    if (!isAllowed && isMainnet) navigate({ pathname: "/deploy" });
add replace option

2023-05-15 04:34 UTC, poomthiti commented on src/lib/pages/upload/index.tsx
> +  const { data: govParams } = useGovParams();
useUploadAccessParams

2023-05-15 04:34 UTC, poomthiti commented on src/lib/pages/codes/components/UploadButton.tsx
> +  const { data: govParams } = useGovParams();
useUploadAccessParams

2023-05-17 04:06 UTC, poomthiti requested changes

2023-05-17 04:06 UTC, poomthiti commented on src/lib/pages/deploy/index.tsx
> +      {address && isMainnet && (
what if some testnet is permissioned

2023-05-17 04:08 UTC, poomthiti commented on src/lib/pages/upload/index.tsx
> +  }, [data, address, isPermissionedNetwork]);
replace this in deploy index page too thanks 🙏

2023-05-18 08:52 UTC, evilpeach approved these changes

2023-05-18 08:55 UTC, merged