Use address type length from example addresses instead of hardcode
alleslabs/celatone-frontend pull request #336
Opened 2023-05-17 02:43 UTC by poomthiti

## Describe your changes

## Demo Link

2023-05-17 04:23 UTC, songwongtp requested changes

2023-05-17 04:23 UTC, songwongtp commented on src/lib/app-provider/hooks/useAddress.ts
>    currentChainRecord: ChainRecord | undefined,
remove currentChainRecord as we don't need it anymore

2023-05-24 11:47 UTC, evilpeach approved these changes

2023-05-24 11:50 UTC, songwongtp approved these changes

2023-05-24 11:50 UTC, songwongtp approved these changes

2023-05-25 03:51 UTC, merged