Feat/Searchbar fetching mechanism
alleslabs/celatone-frontend pull request #345
Opened 2023-05-19 03:02 UTC by poomthiti

## Describe your changes
Apply fetching mechanism and keyboard arrow navigation to searchbar
## Demo Link

2023-05-19 07:24 UTC, bkioshn requested changes

2023-05-19 07:24 UTC, bkioshn commented on src/lib/utils/validate.ts
> +  input !== "" && !!Number(input);
I don't think we need input !== ""

2023-05-19 07:24 UTC, bkioshn commented on src/lib/services/searchService.ts
> +      isAddr && (contractData ? "Contract Address" : "Wallet Address"),
This will cause the problem where if contract address doesn't exist in that network, it will always end up as a wallet address

2023-05-19 08:20 UTC, songwongtp commented on src/lib/layout/Searchbar.tsx
> +      const listItem = document.getElementById(`item-${nextCursor}`);
probably cleaner to just create a function that handles the next cursor then set the value within it self and just call the function in the switch case. With that, these variables would not be needed

2023-05-19 08:20 UTC, songwongtp commented on src/lib/utils/validate.ts
> +export const isBlock = (input: string): boolean =>
handle negative number for both block and code

2023-05-19 11:12 UTC, evilpeach commented on src/lib/utils/validate.ts
> +  input !== "" && !!Number(input);
```tsx
export const isBlock = (input: string): boolean => {
  const numberValue = Number(input);
  return Number.isInteger(numberValue) && numberValue > 0;
};
```

2023-05-19 11:14 UTC, evilpeach commented on src/lib/utils/validate.ts
```tsx
export const isBlock = (input: string): boolean => {
  const numberValue = Number(input);
  return Number.isInteger(numberValue) && numberValue > 0;
};
```

2023-05-20 08:01 UTC, evilpeach requested changes

2023-05-20 08:01 UTC, evilpeach commented on src/lib/layout/Searchbar.tsx
>    const handleSearchChange = (e: ChangeEvent<HTMLInputElement>) => {
Should the first row of the item list be highlighted automatically when some results show in the list?

2023-05-22 11:16 UTC, evilpeach approved these changes

2023-05-22 11:17 UTC, bkioshn approved these changes

2023-05-22 11:17 UTC, merged