feat: refactor block txs
alleslabs/celatone-frontend pull request #347
Opened 2023-05-19 06:44 UTC by songwongtp

## Describe your changes
- move txs accordion arrow to the front of the table
- refactor block txs table to use the common transaction table component

## Demo Link

2023-05-19 08:42 UTC, bkioshn approved these changes

2023-05-20 08:10 UTC, evilpeach requested changes

2023-05-20 08:10 UTC, evilpeach commented on src/lib/services/txService.ts
>          .then(({ transactions }) =>
`then<Transaction[]>`

2023-05-20 08:10 UTC, evilpeach commented on src/lib/services/txService.ts
> +            messages: snakeToCamel(transaction.messages),
add type assertion to `Message[]`

2023-05-22 03:22 UTC, evilpeach approved these changes

2023-05-22 03:32 UTC, merged