Amp/pool nav
alleslabs/celatone-frontend pull request #355
Opened 2023-05-24 07:32 UTC by songwongtp

## Describe your changes
- Add Amp for Pool List page

## Demo Link

2023-05-25 05:00 UTC, poomthiti requested changes

2023-05-25 05:00 UTC, poomthiti commented on src/lib/services/amplitude.tsx
>  ) => track(AmpEvent.USE_EXPAND, { action, component, section });
1. receive props as object 
```ts 
AmpTrackExpand = ({action, component,...}: interface) => {}
```
2. just | "unsupported_pool" and receive another prop (info: object)

2023-05-25 06:14 UTC, bkioshn commented on src/lib/pages/pools/components/supportedSection/index.tsx
> +                const newOrdering = !showNewest;
let's name this `isDesc` so it is the same as unsupported page

2023-05-26 04:02 UTC, poomthiti requested changes

2023-05-26 04:02 UTC, poomthiti commented on src/lib/pages/pools/components/unsupportedSection/index.tsx
> +                  AmpTrackExpandAll(isExpand ? "expand" : "collapse");
personally think this should be outside of setState fn

2023-05-26 04:37 UTC, bkioshn commented on src/lib/services/amplitude.tsx
> +export const AmpTrackUseSort = (order: "Ascending" | "Descending") =>
Should the union type be uncapitalize like the above? just for consistency

2023-05-26 08:39 UTC, poomthiti requested changes

2023-05-26 08:39 UTC, poomthiti commented on src/lib/pages/pools/components/unsupportedSection/index.tsx
> +                    : []
call (prev) => ... for this

2023-05-26 08:59 UTC, poomthiti approved these changes

2023-05-26 09:01 UTC, bkioshn approved these changes

2023-05-26 09:01 UTC, merged