Feat/abstract theme config
alleslabs/celatone-frontend pull request #357
Opened 2023-05-24 12:14 UTC by jennieramida

## Describe your changes

## Demo Link

2023-05-25 07:28 UTC, poomthiti requested changes

2023-05-25 07:28 UTC, poomthiti commented on src/lib/layout/Footer.tsx
> +        </Button>
```tsx
<Link
          href="https://twitter.com/alleslabs"
          target="_blank"
          rel="noopener noreferrer"
          onClick={() => AmpTrack(AmpEvent.ALLESLABS)}
        >
          <Flex
            gap={1}
            align="center"
            _hover={{
              "& svg": {
                opacity: 1,
              },
            }}
          >
            <CustomIcon
              name="alles"
              opacity={0}
              transition="opacity .25s ease-in-out"
            />
            <Text variant="body3" color="text.dark">
              Made by
            </Text>
            <Text
              variant="body3"
              color="secondary.main"
              transition="all .25s ease-in-out"
              _hover={{ color: "secondary.light" }}
            >
              Alles Labs
            </Text>
          </Flex>
        </Link>
```

2023-05-25 07:28 UTC, poomthiti commented on src/lib/layout/Footer.tsx
> +                  <Button variant="ghost-gray" size="xs" px={0}>
remove, if you want hover background just add _hover to Link

2023-05-25 07:28 UTC, poomthiti commented on src/lib/layout/Footer.tsx
> +        </Button>
do the same as commented below

2023-05-25 07:28 UTC, poomthiti commented on src/lib/layout/Footer.tsx
> +                <Button variant="ghost-gray" size="xs" px={1}>
ditto

2023-05-25 07:28 UTC, poomthiti commented on src/lib/layout/Footer.tsx
> +          <Button variant="ghost-gray" size="xs">
ditto

2023-05-26 07:48 UTC, songwongtp requested changes

2023-05-26 07:48 UTC, songwongtp commented on src/config/theme.ts
> +import type { ThemeConfig } from "./type";
create theme folder containing
- index.ts (importing DEFAULT_THEME from default.ts and OSMOSIS_THEME from osmosis.ts)
- default.ts
- osmosis.ts

2023-05-26 07:48 UTC, songwongtp commented on src/lib/components/Seo.tsx
> +    `${currentChainRecord?.chain.pretty_name} Explorer | Celatone`;
change Celatone to `${CURR_THEME.branding.seo.title}` ?

2023-05-26 07:48 UTC, songwongtp commented on src/lib/components/Meta.tsx
> +        content={CURR_THEME.branding.seo.description ?? FALLBACK_DESC}
don't think we need all the FALLBACK variable since all variables in branding.seo are required

2023-05-26 07:48 UTC, songwongtp commented on src/lib/components/Seo.tsx
> +        "A smart contract powered explorer for the Cosmos."
ditto -- remove fallback text or use FALLBACK constants in this file

2023-05-26 07:48 UTC, songwongtp commented on src/lib/components/modal/CodeSnippet.tsx
> +                        theme={CURR_THEME.jsonTheme}
need to check if the specified theme are included in one of the imports, also choose a default if not included

2023-05-26 10:36 UTC, poomthiti approved these changes

2023-05-26 10:38 UTC, bkioshn approved these changes

2023-05-26 10:39 UTC, merged