feat: remove hardcode constant and use from config
alleslabs/celatone-frontend pull request #359
Opened 2023-05-26 04:12 UTC by bkioshn

## Describe your changes
Remove hardcode constant and use from config
Include:
- MAX_CONTRACT_NAME_LENGTH
- MAX_CONTRACT_DESCRIPTION_LENGTH
- MAX_CODE_NAME_LENGTH
- MAX_PROPOSAL_TITLE_LENGTH
- MAX_LIST_NAME_LENGTH

Also move helper function to utils include
- getMaxLengthError to error.ts
- getListIcon to icon.ts

2023-05-26 08:13 UTC, songwongtp approved these changes

2023-06-02 09:08 UTC, evilpeach commented on src/lib/utils/error.ts
> +    : undefined;
So, we should move this file to `app-provider/hooks`

2023-06-03 05:16 UTC, evilpeach requested changes

2023-06-03 05:16 UTC, evilpeach commented on src/lib/hooks/useGetMaxLengthError.ts
> +      return `${field} is too long. (${currentLength}/${maxLength})`;
I recommend that you do the following:
```tsx
import { useCallback } from "react";

import { useCelatoneApp } from "lib/app-provider";

type MaxLengthType =
  | "contract_name"
  | "contract_desc"
  | "code_name"
  | "proposal_title"
  | "list_name";

export const useGetMaxLengthError = () => {
  const { constants } = useCelatoneApp();
  return useCallback(
    (currentLength: number, type: MaxLengthVariant) => {
      const maxLengthMap: Record<MaxLengthType, number> = {
        contract_name: constants.maxContractNameLength,
        contract_desc: constants.maxContractDescriptionLength,
        code_name: constants.maxCodeNameLength,
        proposal_title: constants.maxProposalTitleLength,
        list_name: constants.maxListNameLength,
      };

      const fieldMap: Record<MaxLengthType, string> = {
        contract_name: "Contract name",
        contract_desc: "Contract description",
        code_name: "Code name",
        proposal_title: "Proposal title",
        list_name: "List name",
      };

      const maxLength = maxLengthMap[type] ?? 0;
      const fieldName = fieldMap[type] ?? "Unknown field";

      return `${fieldName} is too long. (${currentLength}/${maxLength})`;
    },
    [
      constants.maxCodeNameLength,
      constants.maxContractDescriptionLength,
      constants.maxContractNameLength,
      constants.maxListNameLength,
      constants.maxProposalTitleLength,
    ]
  );
};
```
and simply supplying 'length' and 'type' as parameters to this function.

2023-06-04 14:59 UTC, evilpeach approved these changes

2023-06-06 03:38 UTC, poomthiti requested changes

2023-06-06 03:38 UTC, poomthiti commented on src/lib/hooks/useGetMaxLengthError.ts
> +      constants.maxProposalTitleLength,
I believe we can just provide `constants` here since the context is memoized

2023-06-06 05:24 UTC, poomthiti approved these changes

2023-06-06 08:29 UTC, merged