fix: unsupported pool search
alleslabs/celatone-frontend pull request #360
Opened 2023-05-26 10:56 UTC by songwongtp

## Describe your changes
- Fix supported pool list cannot be searched with token ID

## Demo Link

2023-05-29 05:01 UTC, bkioshn commented on CHANGELOG.md
> +- [#360](https://github.com/alleslabs/celatone-frontend/pull/360) Fix supported pool list cannot be searched with token ID
add "should not show pagination when data is less than 10"

2023-05-30 04:13 UTC, poomthiti requested changes

2023-05-30 04:13 UTC, poomthiti commented on src/lib/pages/pools/components/unsupportedSection/index.tsx
> +  );
I think you can remove this since the logic is similar to the one in `usePoolListCountQuery` queryFn, configure that one instead

2023-05-30 04:51 UTC, bkioshn approved these changes

2023-05-30 05:38 UTC, poomthiti approved these changes

2023-05-30 05:38 UTC, merged