Feat/recent contracts
alleslabs/celatone-frontend pull request #366
Opened 2023-05-30 08:22 UTC by jennieramida

## Describe your changes

## Demo Link

2023-05-31 05:27 UTC, poomthiti requested changes

2023-05-31 05:27 UTC, poomthiti commented on src/lib/hooks/useContractFilter.ts
> +export const useContractSearchFilter = (keyword: string) =>
I don't think this need to be a hook at all. We can delete this file move the logic to the same file as useRecentContractsData.

2023-05-31 05:27 UTC, poomthiti commented on src/lib/pages/contracts/data.ts
> +};
```tsx
import { useMemo } from "react";

import { useContractStore } from "lib/providers/store";
import { useContractListQuery } from "lib/services/contractService";
import type { ContractInfo } from "lib/types";

interface RecentContractsData {
  recentContracts: ContractInfo[];
  isLoading: boolean;
}

const searchFilterFn = (keyword: string) => (contract: ContractInfo) => {
  const computedKeyword = keyword.trim();
  if (!computedKeyword.length) return true;
  return (
    contract.contractAddress.startsWith(computedKeyword) ||
    contract.name?.toLowerCase().includes(computedKeyword.toLowerCase()) ||
    contract.label.toLowerCase().includes(computedKeyword.toLowerCase())
  );
};

export const useRecentContractsData = (
  keyword: string
): RecentContractsData => {
  const { getContractLocalInfo } = useContractStore();
  const { data: rawRecentContracts = [], isLoading } = useContractListQuery();

  const recentContracts = rawRecentContracts.map<ContractInfo>((contract) => {
    const contractLocalInfo = getContractLocalInfo(contract.contractAddress);
    return {
      ...contract,
      name: contractLocalInfo?.name,
      description: contractLocalInfo?.description,
      tags: contractLocalInfo?.tags,
      lists: contractLocalInfo?.lists,
    };
  });

  return useMemo(() => {
    return {
      recentContracts: recentContracts.filter(searchFilterFn(keyword)),
      isLoading,
    };
  }, [isLoading, recentContracts, keyword]);
};

```

2023-05-31 05:27 UTC, poomthiti commented on src/lib/pages/contracts/index.tsx
> +  });
just use useState, useForm is not necessary here

2023-05-31 05:27 UTC, poomthiti commented on src/lib/pages/contracts/index.tsx
> +        <Text variant="body2" color="text.dark" fontWeight="500">
{500}

2023-05-31 05:27 UTC, poomthiti commented on src/lib/pages/contracts/index.tsx
> +        hasTag={false}
just `withoutTag`

2023-05-31 05:27 UTC, poomthiti commented on src/lib/pages/my-codes/index.tsx
> +  const { keyword, permissionValue } = watch();
prefer to have this refactored to useState, but just leaving a TODO is fine

2023-06-01 03:57 UTC, bkioshn commented on src/lib/pages/contracts/index.tsx
> +  const isSearching = !!searchKeyword;
ditto

2023-06-01 08:12 UTC, poomthiti requested changes

2023-06-01 08:12 UTC, poomthiti commented on src/lib/components/table/contracts/ContractsTable.tsx
> +  withoutTag = false,
remove default

2023-06-01 08:12 UTC, poomthiti commented on src/lib/components/table/contracts/ContractsTableHeader.tsx
> +  withoutTag = false,
remove default

2023-06-01 08:12 UTC, poomthiti commented on src/lib/components/table/contracts/ContractsTableRow.tsx
> +  withoutTag = false,
ditto

2023-06-01 09:03 UTC, poomthiti approved these changes

2023-06-02 08:51 UTC, evilpeach commented on src/lib/pages/contract-details/components/ContractTop.tsx
> +              href: `/projects/${publicProject.publicInfo?.slug}`,
What happens if publicName is undefined.

2023-06-02 08:59 UTC, evilpeach commented on src/lib/pages/my-codes/index.tsx
> +const Codes = observer(() => {
Rename to `MyCodes`

2023-06-02 08:59 UTC, evilpeach commented on src/lib/pages/my-codes/index.tsx
> +export default Codes;
rename it as well

2023-06-02 09:40 UTC, evilpeach approved these changes

2023-06-02 09:41 UTC, merged