feat: implement wasm feature from config
alleslabs/celatone-frontend pull request #369
Opened 2023-05-31 05:22 UTC by bkioshn

## Describe your changes
Implement WASM feature from config

Remove MAX_FILE_SIZE and use storeCodeMaxFileSize
When Wasm flag is disabled, the following path should not be accessed
- /codes
- /contract-list
- /deploy 
- /execute
- /instantiate
- /migrate
- /public-project
- /query
- /recent-codes
- /upload
- /contract 
- /contract-list/instantiated-by-me
- /contract-list/saved-contracts
- /contract-list/[name]
- /admin

2023-06-01 04:48 UTC, poomthiti approved these changes

2023-06-01 04:53 UTC, poomthiti commented
I think we should create a custom hook for checking wasm path redirect and amptrack. Maybe add a refactor task later @evilpeach

2023-06-01 07:48 UTC, songwongtp requested changes

2023-06-01 07:48 UTC, songwongtp commented on src/lib/pages/codes/index.tsx
> +    else if (router.isReady) AmpTrack(AmpEvent.TO_MY_CODES);
ditto

2023-06-06 08:49 UTC, evilpeach requested changes

2023-06-06 08:49 UTC, evilpeach commented on src/lib/pages/deploy/index.tsx
> +  }, [navigate, router.isReady]);
ditto

2023-06-06 08:49 UTC, evilpeach commented on src/lib/pages/contract-list/slug.tsx
> +// eslint-disable-next-line sonarjs/cognitive-complexity
can we remove?

2023-06-06 08:49 UTC, evilpeach commented on src/lib/pages/code-details/index.tsx
> +  }, [navigate, router.isReady]);
remove

2023-06-06 08:49 UTC, evilpeach commented on src/lib/pages/contract-details/index.tsx
> +  }, [navigate, router.isReady]);
remove

2023-06-06 09:04 UTC, evilpeach approved these changes

2023-06-06 09:07 UTC, merged