fix(components): fix assign me and fix color in redelegation
alleslabs/celatone-frontend pull request #371
Opened 2023-06-06 09:06 UTC by jennieramida

## Describe your changes

## Demo Link

2023-06-07 04:21 UTC, poomthiti requested changes

2023-06-07 04:21 UTC, poomthiti commented on src/lib/pages/faucet/index.tsx
> +            isDisable={!walletAddress || address === walletAddress}
remove !walletAddress, the component already checks for this condition

2023-06-07 04:21 UTC, poomthiti commented on src/lib/pages/instantiate/instantiate.tsx
> +                isDisable={!address || watchAdminAddress === address}
ditto

2023-06-08 02:55 UTC, evilpeach commented on CHANGELOG.md
> +- [#371](https://github.com/alleslabs/celatone-frontend/pull/371) Refactor assign me component and fix color in redelegation page
Please rebase from develop branch in order to fix the confilct.

2023-06-08 03:58 UTC, evilpeach approved these changes
lgtm

2023-06-08 04:15 UTC, poomthiti approved these changes

2023-06-08 04:15 UTC, merged