Fix/token denom
alleslabs/celatone-frontend pull request #393
Opened 2023-06-15 09:04 UTC by songwongtp

## Describe your changes
- Fix format denom function

## Demo Link

2023-06-15 10:21 UTC, poomthiti requested changes

2023-06-15 10:21 UTC, poomthiti commented on src/lib/utils/formatter/denom.ts
> +const getTokenLabel = (denom: string) => {
duplicate name

2023-06-15 10:21 UTC, poomthiti commented on src/lib/utils/formatter/tokenType.ts
> +export const getTokenLabel = (denom: string, symbol?: string) => {
duplicate name

2023-06-15 10:21 UTC, poomthiti commented on src/lib/utils/formatter/denom.ts
> +const getTokenLabel = (denom: string) => {
is this still necessary?

2023-06-16 04:57 UTC, evilpeach approved these changes

2023-06-16 05:04 UTC, poomthiti approved these changes

2023-06-16 05:05 UTC, merged