feat: improve dropdown and combo box interaction
alleslabs/celatone-frontend pull request #408
Opened 2023-06-27 06:56 UTC by poomthiti

## Describe your changes

## Demo Link

2023-06-28 03:02 UTC, songwongtp commented
clicking `DropdownChevron` first doesn't properly show the option list

2023-06-28 03:03 UTC, songwongtp requested changes
clicking `DropdownChevron` first doesn't properly show the option list

2023-07-04 05:31 UTC, bkioshn approved these changes

2023-07-18 07:10 UTC, evilpeach approved these changes

2023-07-18 07:10 UTC, merged