feat: add test case for assetValue and funds
alleslabs/celatone-frontend pull request #414
Opened 2023-06-30 10:44 UTC by bkioshn

## Describe your changes
Add test for 
- `utils/funds.ts`
- `utils/assetValue.ts`

Remove 
- `utils/isDecimalNumber.ts`
- `utils/number.ts`

2023-07-03 10:43 UTC, songwongtp requested changes

2023-07-03 10:43 UTC, songwongtp commented on src/lib/utils/assetValue.test.ts
> +    value: big(200) as U<Token<Big>>,
value type is `USD<Big>`

2023-07-03 10:43 UTC, songwongtp commented on src/lib/utils/assetValue.test.ts
> +    value: big(3500) as U<Token<Big>>,
ditto

2023-07-03 10:43 UTC, songwongtp commented on src/lib/utils/assetValue.test.ts
> +      value: big(3700) as U<Token<Big>>,
ditto

2023-07-03 10:43 UTC, songwongtp commented on src/lib/utils/assetValue.test.ts
> +    expect(addTokenWithValue(tokenWithValue1, tokenWithValue2)).toEqual(
also test `addTokenWithValue(tokenWithValue2, tokenWithValue1)`

2023-07-05 09:00 UTC, evilpeach requested changes

2023-07-13 03:34 UTC, evilpeach commented on src/lib/utils/assetValue.ts
> +  if (Number.isNaN(Number(balance.amount)) || !balance.amount.length)
Please add the `trim()` function and also introduce a test case for when `balance.amount` is a space.

2023-07-13 04:19 UTC, evilpeach approved these changes

2023-07-13 04:30 UTC, merged