feat: retrieve asset prices only when necessary (/prices url path)
alleslabs/celatone-frontend pull request #450
Opened 2023-07-18 09:27 UTC by poomthiti

## Describe your changes

## Demo Link

2023-07-19 08:00 UTC, bkioshn requested changes

2023-07-19 08:00 UTC, bkioshn commented on src/lib/pages/pools/components/supportedSection/index.tsx
> +  const { assetInfos } = useAssetInfos({ withPrices: false });
This should be true

2023-07-20 03:19 UTC, evilpeach approved these changes
lgtm

2023-07-20 03:26 UTC, bkioshn approved these changes

2023-07-20 03:30 UTC, merged