feat: implement schema store and unit test
alleslabs/celatone-frontend pull request #455
Opened 2023-07-21 09:12 UTC by poomthiti

## Describe your changes

## Demo Link

2023-07-27 04:45 UTC, evilpeach requested changes

2023-07-27 04:45 UTC, evilpeach commented on src/lib/stores/schema.ts
> +
I would prefer to utilize the `RJSFSchema` type from `@rjsf/utils` instead.

2023-07-27 04:45 UTC, evilpeach commented on src/lib/stores/schema.ts
> +interface InternalSchema {
No need to declare it here.

2023-07-27 04:45 UTC, evilpeach commented on src/lib/stores/schema.ts
> +  getQuerySchemaFormArray(codeHash: string) {
I think we can simplify this by using `getQuerySchema` and defining the output interface. This approach will make the code more clear.

2023-07-27 04:45 UTC, evilpeach commented on src/lib/stores/schema.ts
> +  getExecuteSchemaFormArray(codeHash: string) {
ditto

2023-08-04 05:52 UTC, evilpeach approved these changes

2023-08-04 06:10 UTC, songwongtp approved these changes

2023-08-04 06:37 UTC, merged