Feat/initia module detail
alleslabs/celatone-frontend pull request #516
Opened 2023-09-04 10:53 UTC by jennieramida

## Describe your changes

## Demo Link

2023-09-05 07:20 UTC, poomthiti requested changes

2023-09-05 07:20 UTC, poomthiti commented on src/lib/pages/module-details/components/ModuleTop.tsx
> +              whiteSpace="nowrap"
declare const baseTextStyle: TextProps = {...} at the top of the file and apply like this {...baseTextStyle}

2023-09-05 07:20 UTC, poomthiti commented on src/lib/pages/module-details/index.tsx
> +  const txTableHeaderId = "ModuleTxsTableHeader";
declare outside of component

2023-09-06 03:34 UTC, poomthiti approved these changes

2023-09-08 09:24 UTC, evilpeach approved these changes

2023-09-08 09:24 UTC, merged