Feat/initia publish module
alleslabs/celatone-frontend pull request #517
Opened 2023-09-05 06:21 UTC by jennieramida

## Describe your changes

## Demo Link

2023-09-06 05:06 UTC, poomthiti requested changes

2023-09-06 05:06 UTC, poomthiti commented on src/lib/pages/publish-module/index.tsx
> +  ];
move outside of component

2023-09-06 05:06 UTC, poomthiti commented on src/lib/pages/publish-module/index.tsx
> +              pr={1}
p="0 4px"

2023-09-07 03:42 UTC, jennieramida commented on src/lib/pages/publish-module/components/Footer.tsx
> +        <Flex flex="5" align="center" justify="space-between" h="full" w="full">
false ai poom juke

2023-09-07 03:43 UTC, jennieramida commented on src/lib/pages/publish-module/components/PolicyCard.tsx
> +            <Flex mt={1}>
✅

2023-09-08 09:49 UTC, merged