Feat/initia module detail function
alleslabs/celatone-frontend pull request #545
Opened 2023-09-25 10:18 UTC by jennieramida

## Describe your changes

## Demo Link

2023-09-29 10:37 UTC, songwongtp commented
add changelog

2023-10-16 09:46 UTC, evilpeach requested changes

2023-10-16 09:46 UTC, evilpeach commented on src/lib/components/module/StructCard.tsx
> +                      size="sm"
add key

2023-10-16 09:46 UTC, evilpeach commented on src/lib/components/module/FunctionDetailCard.tsx
> +        <LabelText
remove `return`

2023-10-16 09:46 UTC, evilpeach commented on src/lib/components/module/FunctionDetailCard.tsx
> +  };
```suggestion
    const fnColor = isView ? "primary.main" : "accent.main";
```

2023-10-16 09:46 UTC, evilpeach commented on src/lib/pages/module-details/index.tsx
> +                    p={4}
add key

2023-10-17 10:16 UTC, evilpeach approved these changes

2023-10-17 10:17 UTC, merged