fix(components): fix pool type alignment in pool card
alleslabs/celatone-frontend pull request #560
Opened 2023-10-11 11:01 UTC by jennieramida

## Describe your changes

## Demo Link

2023-10-11 11:59 UTC, songwongtp requested changes

2023-10-11 11:59 UTC, songwongtp commented on src/lib/pages/pools/components/PoolHeader.tsx
> +        <Flex direction="column">
change to `<div>`

2023-10-12 14:42 UTC, songwongtp approved these changes

2023-10-12 15:33 UTC, evilpeach approved these changes

2023-10-12 15:37 UTC, evilpeach approved these changes

2023-10-12 16:26 UTC, merged