fix(components): add shortcut for contract state and clean up transition
alleslabs/celatone-frontend pull request #586
Opened 2023-10-26 07:46 UTC by jennieramida

## Describe your changes

## Demo Link

2023-10-26 08:08 UTC, songwongtp requested changes

2023-10-26 08:08 UTC, songwongtp commented on src/lib/pages/contract-details/index.tsx
> +  return (
implicit return

2023-11-01 04:51 UTC, evilpeach approved these changes

2023-11-01 05:18 UTC, songwongtp approved these changes

2023-11-01 05:18 UTC, merged