feat: amp module detail and breadcrumb
alleslabs/celatone-frontend pull request #633
Opened 2023-11-23 08:18 UTC by sunzsolo

2023-11-24 05:25 UTC, songwongtp requested changes

2023-11-24 05:25 UTC, songwongtp commented on CHANGELOG.md
> +- [#633](https://github.com/alleslabs/celatone-frontend/pull/633) feat: amp module detail and breadcrumb
remove `feat: `

2023-11-24 05:25 UTC, songwongtp commented on src/lib/amplitude/track-event/trackInteraction.ts
> +    | "Module Struct Accordian"
use snake case e.g. `module_function...`

2023-11-24 07:36 UTC, evilpeach commented on src/lib/amplitude/track-event/trackInteraction.ts
> +    | "module_function_accordian"
accordion

2023-11-24 07:36 UTC, evilpeach commented on src/lib/amplitude/track-event/trackInteraction.ts
> +    | "module_struct_accordian"
ditto

2023-11-24 07:57 UTC, evilpeach commented on src/lib/pages/module-details/index.tsx
> +      track(AmpEvent.USE_NAVIGATING_BUTTON, { Label: fnType ?? "History" });
`label`

2023-11-24 08:12 UTC, evilpeach approved these changes

2023-11-27 11:27 UTC, songwongtp requested changes

2023-11-27 11:27 UTC, songwongtp commented on src/lib/pages/module-details/index.tsx
> +                            table: "Published Event",
`Module Published Events`

2023-11-27 11:27 UTC, songwongtp commented on src/lib/pages/module-details/components/ModuleStruct.tsx
> +                "[Module Detail] Struct"
`Module Struct`

2023-11-27 11:27 UTC, songwongtp commented on src/lib/pages/module-details/components/ModuleStruct.tsx
> +              trackUseViewJSON("Module Detail Struct");
`Module Struct`

2023-11-27 11:27 UTC, songwongtp commented on src/lib/pages/module-details/index.tsx
> +                            table: "Module transactions",
`Module Transactions`

2023-11-28 03:57 UTC, songwongtp approved these changes

2023-11-28 07:16 UTC, merged