feat(utils): add amplitude for module interaction page
alleslabs/celatone-frontend pull request #637
Opened 2023-11-28 06:51 UTC by sunzsolo

2023-11-29 03:40 UTC, songwongtp requested changes

2023-12-04 03:30 UTC, evilpeach commented on src/lib/pages/interact/component/common/FunctionAccordion.tsx
> +  amptracktab,
amptractTab

2023-12-04 03:45 UTC, evilpeach requested changes

2023-12-04 03:45 UTC, evilpeach commented on src/lib/pages/interact/component/common/FunctionAccordion.tsx
> +                info: { Tab: amptracktab },
```suggestion
                info: { tab: amptrackTab },
```

2023-12-04 03:45 UTC, evilpeach commented on src/lib/pages/interact/component/drawer/selector/ModuleSelectorInput.tsx
> +        trackUseModuleSelectionInputFill(addr, !!moduleName, !!functionName);
move to `handleSubmit` fn

2023-12-04 03:45 UTC, evilpeach commented on src/lib/pages/interact/component/drawer/selector/ModuleSelectorInput.tsx
> +    [functionName, handleSubmit, moduleName, addr]
remove unused

2023-12-04 03:45 UTC, evilpeach commented on src/lib/pages/interact/component/drawer/selector/ModuleSelectorInput.tsx
> +            trackUseModuleSelectionInputFill(
ditto

2023-12-06 11:24 UTC, evilpeach approved these changes

2023-12-06 11:50 UTC, songwongtp requested changes

2023-12-06 11:50 UTC, songwongtp commented on src/lib/pages/interact/component/common/FunctionAccordion.tsx
> +  amptrackTab: string;
move below `setSelectedFn`

2023-12-06 11:50 UTC, songwongtp commented on src/lib/pages/interact/component/common/FunctionAccordion.tsx
> +          </Flex>
move `</Flex>` to between line 71 and 72

2023-12-07 11:51 UTC, merged