feat(pages): add recent modules page
alleslabs/celatone-frontend pull request #654
Opened 2023-12-07 09:05 UTC by James0126

## Describe your changes
add recent modules page

## Demo Link
[Demo](https://initia-celatone-frontend-git-feature-initiarec-f34909-alleslabs.vercel.app/)

2023-12-12 05:37 UTC, songwongtp requested changes

2023-12-12 05:37 UTC, songwongtp commented on src/lib/app-provider/env.ts
> +  MODULES_DATA = "CELATONE_QUERY_MODULES_DATA",
`MODULE = "CELATONE_QUERY_MODULES"`

2023-12-12 05:37 UTC, songwongtp commented on src/lib/types/move/module.ts
> +export interface RecentModule {
move to `module.ts` and make the `zod` type

2023-12-12 05:37 UTC, songwongtp commented on src/lib/types/move/module.ts
> +  };
we did some change to the API, and flatten the `block` field to `height` and `lastUpdated`

2023-12-13 11:20 UTC, evilpeach approved these changes

2023-12-13 11:25 UTC, songwongtp approved these changes

2023-12-13 11:25 UTC, merged