fix(components): contract list card and microcopies
alleslabs/celatone-frontend pull request #674
Opened 2023-12-18 03:27 UTC by jennieramida

## Describe your changes

## Demo Link

2023-12-20 11:20 UTC, songwongtp requested changes

2023-12-20 11:20 UTC, songwongtp commented on src/lib/components/select-contract/ContractListCard.tsx
> +      <Flex gap={4} w="full" alignItems="center">
can we combine these 2?

2023-12-20 11:31 UTC, songwongtp approved these changes

2023-12-21 04:03 UTC, evilpeach approved these changes

2023-12-21 04:04 UTC, merged