Feat/nft amplitude
alleslabs/celatone-frontend pull request #727
Opened 2024-01-15 10:46 UTC by sunzsolo

Adding Amplitude to NFTs

2024-01-15 15:57 UTC, songwongtp requested changes

2024-01-15 15:57 UTC, songwongtp commented on src/lib/components/nft/NftCard.tsx
> +        }}
() => track(AmpEvent.USE_NFT_CARD, { showCollection });

2024-01-15 15:57 UTC, songwongtp commented on src/lib/pages/nft-collection-details/CollectionDetailsBody.tsx
> +import {
why do we need this file?

2024-01-15 15:57 UTC, songwongtp commented on src/lib/pages/nft-collection-details/index.tsx
> +export const InvalidCollection = () => (
remove export

2024-01-15 15:57 UTC, songwongtp commented on src/lib/pages/nft-collection-details/index.tsx
> +export const tabHeaderId = "collectionDetailTab";
ditto

2024-01-15 15:57 UTC, songwongtp commented on src/lib/pages/nft-collections/components/Collections.tsx
>      <Box>
change to fragment `<>`

2024-01-15 16:16 UTC, songwongtp requested changes

2024-01-15 16:16 UTC, songwongtp commented on src/lib/pages/nft-collection-details/index.tsx
> +export const tabHeaderId = "collectionDetailTab";
line 110 change to fragment `<>`

2024-01-15 16:16 UTC, songwongtp commented on src/lib/pages/nft-collection-details/components/tables/activities/index.tsx
> +        amptrackSection="activities-in-this-collection-search"
line 47, discuss with @jennieramida

2024-01-16 03:23 UTC, sunzsolo commented on src/lib/pages/nft-collection-details/CollectionDetailsBody.tsx
> +import {
Deleted

2024-01-16 03:25 UTC, sunzsolo commented on src/lib/pages/nft-collection-details/index.tsx
> +export const InvalidCollection = () => (
fixed

2024-01-16 03:25 UTC, sunzsolo commented on src/lib/pages/nft-collection-details/index.tsx
> +export const tabHeaderId = "collectionDetailTab";
ditto

2024-01-16 03:26 UTC, sunzsolo commented on src/lib/pages/nft-collections/components/Collections.tsx
>      <Box>
fixed

2024-01-16 03:27 UTC, sunzsolo commented on src/lib/pages/nft-collection-details/index.tsx
> +export const tabHeaderId = "collectionDetailTab";
fixed

2024-01-16 03:40 UTC, sunzsolo commented on src/lib/pages/nft-collection-details/components/tables/activities/index.tsx
> +        amptrackSection="activities-in-this-collection-search"
fixed

2024-01-16 04:01 UTC, sunzsolo commented on src/lib/components/nft/NftCard.tsx
> +        }}
fixed

2024-01-16 06:29 UTC, songwongtp commented on src/lib/pages/nft-collection-details/components/tables/activities/ActivitiesTableMobileCard.tsx
>          <Flex align="center" gap={2}>
try removing this

2024-01-16 06:30 UTC, songwongtp commented on src/lib/pages/nft-collection-details/index.tsx
> +            onClick={() => {
`() => track(AmpEvent.USE_NFT_VIEW_RESOURCE_CTA, {
                amptrackSection: "nft-collection-details",
              })`

2024-01-16 06:33 UTC, sunzsolo commented on src/lib/pages/nft-collection-details/index.tsx
> +            onClick={() => {
fixed

2024-01-17 09:11 UTC, songwongtp approved these changes

2024-01-17 10:39 UTC, evilpeach commented on src/lib/pages/nft-collection-details/data.ts
> +  const supplyData = collectionSupplyResource
I think we should declare type for `supplyData`.

2024-01-17 10:41 UTC, evilpeach commented on src/lib/pages/nft-collection-details/data.ts
> +    ? JSON.parse(royalty.items[0].moveResource)
If the length of items is zero, could that potentially cause a problem?

2024-01-17 18:18 UTC, evilpeach approved these changes

2024-01-18 02:26 UTC, merged