feat(components): add proposal detail page structure
alleslabs/celatone-frontend pull request #731
Opened 2024-01-18 08:16 UTC by jennieramida

## Describe your changes

## Demo Link

2024-01-23 03:10 UTC, evilpeach requested changes

2024-01-23 03:10 UTC, evilpeach commented on src/lib/pages/proposal-details/index.tsx
> +  const proposalId = parseInt(router.query.id as string, 10);
Let's use zod. See the other details page as example

2024-01-25 11:00 UTC, songwongtp requested changes

2024-01-25 11:00 UTC, songwongtp commented on src/lib/pages/proposal-details/components/ProposalDetailsBody.tsx
> +export const ProposalDetailBody = ({
ProposalDetailsBody

2024-01-25 11:00 UTC, songwongtp commented on src/lib/pages/proposal-details/components/ProposalDetailsBody.tsx
> +
handle invalid proposal in here

2024-01-25 11:00 UTC, songwongtp commented on src/lib/pages/proposal-details/index.tsx
> +};
remove

2024-01-25 11:00 UTC, songwongtp commented on src/lib/pages/proposal-details/index.tsx
> +export const ProposalDetails = () => {
for consistency, remove export

2024-01-25 11:00 UTC, songwongtp commented on src/lib/pages/proposal-details/index.tsx
> +};
`export default ProposalDetails`

2024-01-25 11:00 UTC, songwongtp commented on src/lib/pages/proposal-details/components/ValidatorVotesTable.tsx
> +}
new line

2024-01-25 11:00 UTC, songwongtp commented on src/lib/pages/proposal-details/index.tsx
> +import { ProposalDetailBody } from "./components/ProposalDetailsBody";
add `index.ts` in the component dir with
```
export * from "./ProposalDetailsBody";
export * from "./ProposalTop";
```
then import from just `./components` instead

2024-01-25 16:51 UTC, jennieramida commented on src/lib/pages/proposal-details/components/ProposalDetailsBody.tsx
> +
already handle in index page

2024-01-26 07:16 UTC, evilpeach commented on src/lib/components/MobileGuard.tsx
> +    pathName.includes(`/proposals`) ||
I think we should update as following: 
```tsx
export const MobileGuard = ({ children }: MobileGuardProps) => {
  const router = useRouter();
  const pathName = router.asPath;
  const isMobile = useMobile();
  const isResponsive =
    pathName.includes(`/accounts`) ||
    pathName.includes(`/txs`) ||
    pathName.includes(`/blocks`) ||
    pathName.includes(`/projects`) ||
    pathName.includes(`/codes`) ||
    pathName.includes(`/nft-collections`) ||
    pathName.includes(`/query`) ||
    pathName.includes(`/404`) ||
    pathName.includes(`/proposals`) ||
    // wasm
    pathName.includes(`/contracts/`) ||
    // move
    pathName.includes(`/modules`);

  if (isResponsive && isMobile) return <>{children}</>;
  if (!isResponsive && isMobile) return <NoMobile />;
  return <>{children}</>;
};
```

2024-01-26 10:51 UTC, songwongtp approved these changes

2024-01-26 12:11 UTC, evilpeach approved these changes

2024-01-27 03:28 UTC, merged