Feat/cfe 206 proposal top
alleslabs/celatone-frontend pull request #745
Opened 2024-01-22 11:39 UTC by jennieramida

## Describe your changes

## Demo Link

2024-01-30 07:23 UTC, songwongtp requested changes

2024-01-30 07:23 UTC, songwongtp commented on package.json
> +    "@interchain-ui/react": "1.20.7",
revert

2024-01-30 07:23 UTC, songwongtp requested changes

2024-01-30 07:23 UTC, songwongtp commented on package.json
> +    "@interchain-ui/react": "1.20.7",
ditto

2024-02-01 06:23 UTC, songwongtp requested changes

2024-02-01 06:23 UTC, songwongtp commented on src/lib/components/ExplorerLink.tsx
> +
remove empty line

2024-02-01 06:23 UTC, songwongtp commented on src/lib/components/table/proposals/ProposalsTableMobileCard.tsx
> +      }}
onClick={() => onCardSelect(proposal.id)}

2024-02-01 06:28 UTC, evilpeach requested changes

2024-02-01 06:28 UTC, evilpeach commented on package.json
> +    "storybook-react-context": "^0.6.0",
remove for now

2024-02-01 06:28 UTC, evilpeach commented on src/lib/services/proposal.ts
> +          ...deposit,
Let's address each property individually, given that the `deposit` includes a `tx_hash` property.

2024-02-01 07:24 UTC, songwongtp requested changes

2024-02-01 08:57 UTC, evilpeach approved these changes

2024-02-01 09:35 UTC, songwongtp approved these changes

2024-02-01 10:24 UTC, merged