Feat/cfe 208 proposal description
alleslabs/celatone-frontend pull request #759
Opened 2024-01-31 07:34 UTC by jennieramida

## Describe your changes

## Demo Link

2024-02-01 10:50 UTC, songwongtp requested changes

2024-02-01 10:50 UTC, songwongtp commented on src/lib/pages/proposal-details/components/ProposalOverview.tsx
> +            >
combine with components in the renderMetadata fn

2024-02-01 10:50 UTC, songwongtp commented on src/lib/pages/proposal-details/components/ProposalOverview.tsx
> +                gap={4}
remove gap

2024-02-01 10:50 UTC, songwongtp commented on src/lib/pages/proposal-details/components/ProposalOverview.tsx
> +};
new line

2024-02-01 10:50 UTC, songwongtp commented on src/lib/pages/proposal-details/components/ProposalOverview.tsx
> +}
new line

2024-02-01 10:50 UTC, songwongtp commented on src/lib/components/__stories__/Markdown.stories.ts
> +## Lists
for consistency
"const list = `## Lists"

2024-02-01 11:14 UTC, evilpeach commented on src/lib/pages/proposal-details/index.tsx
> +            <ProposalOverview proposalData={proposalData} />
data.info

2024-02-01 11:26 UTC, evilpeach commented on src/lib/pages/proposal-details/components/ProposalOverview.tsx
> +  return urlRegex.test(metadata);
I think we can use Zod to determine whether input is a URL.

2024-02-04 07:36 UTC, songwongtp approved these changes

2024-02-04 07:36 UTC, songwongtp commented on src/lib/utils/validate.ts
> +export const isUrl = (string: string): boolean => {
Move this to line 17 (currently is in the middle of hex related fns)

2024-02-05 06:35 UTC, evilpeach approved these changes

2024-02-05 06:35 UTC, merged