[After #763] Feat/status summary body
alleslabs/celatone-frontend pull request #766
Opened 2024-02-06 07:45 UTC by songwongtp

## Describe your changes

## Demo Link

2024-02-08 07:15 UTC, evilpeach requested changes

2024-02-09 08:00 UTC, songwongtp commented on src/lib/pages/proposal-details/index.tsx
> +  }, [router.isReady]);
keep it like this for the consistency over all pages. if needed to change, then let's open a new PR and apply to all pages

2024-02-09 08:01 UTC, songwongtp commented on src/lib/pages/proposal-details/index.tsx
> +  }, [router.isReady]);
also should we track invalid page?

2024-02-13 04:22 UTC, evilpeach approved these changes

2024-02-13 04:28 UTC, merged