Feature/cfe 329 format.test.ts unit test
alleslabs/celatone-frontend pull request #769
Opened 2024-02-06 09:42 UTC by Poafs1

## Describe your changes
Add unit test for format.test.ts

2024-02-06 09:51 UTC, songwongtp approved these changes

2024-02-06 10:56 UTC, evilpeach requested changes

2024-02-07 03:15 UTC, Poafs1 commented on CHANGELOG.md
> +- [#769](https://github.com/alleslabs/celatone-frontend/pull/768) Add unit test for format.test.ts on shortenName function
👍🏼

2024-02-07 03:18 UTC, evilpeach approved these changes
Lgtm

2024-02-07 03:29 UTC, merged