fix(components): add expand collapse all to proposal message accordion
alleslabs/celatone-frontend pull request #776
Opened 2024-02-09 10:04 UTC by jennieramida

## Describe your changes

## Demo Link

2024-02-09 10:49 UTC, songwongtp requested changes

2024-02-09 10:49 UTC, songwongtp commented on src/lib/pages/proposal-details/components/proposal-overview/ProposalMessageCard.tsx
> +            >
do we need this `div`?

2024-02-09 10:49 UTC, songwongtp commented on src/lib/pages/proposal-details/components/proposal-overview/ProposalMessageCard.tsx
> +  return (
remove `return`

2024-02-09 10:49 UTC, songwongtp commented on src/lib/pages/proposal-details/components/proposal-overview/ProposalMessageCard.tsx
> +            >
likely the cause of the snap collapse animation

2024-02-09 10:50 UTC, songwongtp requested changes

2024-02-09 10:50 UTC, songwongtp commented on CHANGELOG.md
> +- [#771](https://github.com/alleslabs/celatone-frontend/pull/771) Adjust proposal detail
extra changelog

2024-02-13 08:17 UTC, evilpeach commented on src/lib/pages/proposal-details/components/proposal-overview/ProposalMessages.tsx
> +            key={`msg-${item}`}
```
  key={`msg-${item["@type"]}`}
  ```

2024-02-13 08:21 UTC, evilpeach commented on src/lib/pages/proposal-details/components/proposal-overview/ProposalMessages.tsx
> +              "account detail resources Tab"
account detail?

2024-02-14 08:39 UTC, songwongtp approved these changes

2024-02-14 08:44 UTC, evilpeach approved these changes

2024-02-14 08:53 UTC, merged