Feat/cfe 58 UI validator detail
alleslabs/celatone-frontend pull request #801
Opened 2024-03-02 01:10 UTC by jennieramida

## Describe your changes

## Demo Link

2024-03-08 08:37 UTC, songwongtp requested changes

2024-03-10 16:59 UTC, jennieramida commented on src/lib/pages/validator-details/components/ValidatorStatusTag.tsx
> +// }
don't know if will be needed in the future?  will delete it for now then

2024-03-11 10:46 UTC, evilpeach approved these changes

2024-03-11 10:47 UTC, songwongtp approved these changes

2024-03-11 10:47 UTC, merged