Fix/ux improvement
alleslabs/celatone-frontend pull request #806
Opened 2024-03-05 07:46 UTC by jennieramida

## Describe your changes

## Demo Link

2024-03-06 03:59 UTC, songwongtp requested changes

2024-03-06 03:59 UTC, songwongtp commented on src/lib/components/asset/UnsupportedAssetTitle.tsx
> +    // borderRadius="8px 8px 0px 0px"
remove comment

2024-03-06 03:59 UTC, songwongtp commented on src/lib/pages/tx-details/components/tx-message/TxMsgDetails.tsx
> +// )
remove

2024-03-11 10:45 UTC, evilpeach approved these changes

2024-03-11 10:45 UTC, merged