[CFE-381]: Feature - bonded changes transaction
alleslabs/celatone-frontend pull request #831
Opened 2024-03-18 06:52 UTC by Poafs1

2024-03-19 09:35 UTC, songwongtp approved these changes

2024-03-19 09:35 UTC, songwongtp commented on src/lib/services/validator.ts
> +    sender: zValidatorAddr,
zBechAddr

2024-03-19 10:31 UTC, songwongtp requested changes

2024-03-19 10:31 UTC, songwongtp commented on src/lib/pages/validator-details/components/tables/related-transactions/RelatedTransactionsTable.tsx
> +  delegationRelatedTxs = [],
remove default `[]`

2024-03-19 10:31 UTC, songwongtp commented on src/lib/pages/validator-details/components/tables/related-transactions/RelatedTransactionsTable.tsx
> +  if (isLoading) return <Loading />;
```
if (!delegationRelatedTxs) return <ErrorFetching dataName="delegation related txs" />
```

2024-03-19 10:31 UTC, songwongtp commented on src/lib/pages/validator-details/components/tables/related-transactions/RelatedTransactionsTableRow.tsx
> +  return (
implicite return

2024-03-19 10:31 UTC, songwongtp commented on src/lib/pages/validator-details/components/tables/related-transactions/RelatedTransactionsTable.tsx
let's make this file `index.tsx` of this directory

2024-03-19 10:31 UTC, songwongtp commented on src/lib/pages/validator-details/components/tables/related-transactions/RelatedTransactionsMobileCard.tsx
MobileCard is called inside of the Table component in this case is `RelatedTransactionsTable`. Please see the other table as an example

2024-03-19 10:31 UTC, songwongtp commented on src/lib/pages/validator-details/components/bonded-token-changes/index.tsx
> +        )}
```
{
  !isMobile && (
    <TableTitle
              title="Delegation-Related Transactions"
              count={data?.total ?? 0}
              id={tableHeaderId}
              helperText="Shows transactions relevant to changes in delegated tokens, excluding any token reduction due to slashing."
            />
  )
  <RelatedTransactionTable
              delegationRelatedTxs={data?.items}
              isLoading={isLoading}
              assetInfos={assetInfos}
   />
}
```

2024-03-20 06:26 UTC, songwongtp requested changes

2024-03-20 06:26 UTC, songwongtp commented on src/lib/pages/validator-details/components/tables/related-transactions/RelatedTransactionsBondedTokenChanges.tsx
> +  token: Coin;
`coin: Coin`

2024-03-20 06:26 UTC, songwongtp commented on src/lib/pages/validator-details/components/tables/related-transactions/RelatedTransactionsBondedTokenChanges.tsx
> +  );
```
const token = coinToTokenWithValue(
    coin.denom,
    coin.amount,
    assetInfos
  );
```

2024-03-20 06:26 UTC, songwongtp commented on src/lib/pages/validator-details/components/tables/related-transactions/index.tsx
> +      {delegationRelatedTxs?.map((delegationRelatedTx) => (
remove `?`

2024-03-20 06:26 UTC, songwongtp commented on src/lib/services/validator.ts
> +  }));
this is already correct, but you can also do
```
z.object({
  tx_hash: z.string().transform(parseTxHash),
  ...
}).transform(snakeToCamel);
```

2024-03-20 06:35 UTC, songwongtp requested changes

2024-03-20 06:35 UTC, songwongtp commented on src/lib/pages/validator-details/components/tables/related-transactions/RelatedTransactionsBondedTokenChanges.tsx
> +    tokenWithValue.amount,
let's do
```
const formattedAmount = `{isPositiveAmount ? "+":"-"}{formatUTokenWithPrecision(tokenWithValue.amount.abs(), tokenWithValue.precision ?? 0, false, 2)}`
```

2024-03-20 06:35 UTC, songwongtp commented on src/lib/pages/validator-details/components/tables/related-transactions/RelatedTransactionsBondedTokenChanges.tsx
> +            {isPositiveAmount ? `+${formattedAmount}` : formattedAmount}
`{formattedAmount}` as we already handle +/- above

2024-03-20 06:35 UTC, songwongtp commented on src/lib/utils/formatter/token.ts
> +  allowNegativeValue = false
remove

2024-03-20 06:35 UTC, songwongtp commented on src/lib/utils/formatter/token.ts
>    }
revert back

2024-03-20 09:49 UTC, songwongtp requested changes

2024-03-20 09:49 UTC, songwongtp commented on src/lib/pages/validator-details/components/tables/related-transactions/RelatedTransactionsBondedTokenChanges.tsx
> +          ({formatPrice(tokenWithValue.value?.abs() as USD<BigSource>)})
`tokenWithValue.value ? formatPrice(tokenWithValue.value.abs() as USD<BigSource> : "-"`

2024-03-21 03:33 UTC, songwongtp approved these changes

2024-03-21 04:03 UTC, songwongtp commented on src/lib/pages/validator-details/components/tables/related-transactions/RelatedTransactionsBondedTokenChanges.tsx
>            </Text>{" "}
remove `{" "}`

2024-03-21 08:27 UTC, evilpeach commented on src/lib/pages/validator-details/components/tables/related-transactions/index.tsx
> +  onRowSelect,
It's no need pass from parent. Let's create navigate function here.

2024-03-21 09:20 UTC, evilpeach approved these changes

2024-03-22 03:35 UTC, merged