[CFE-403] Fix(components): voting power chart
alleslabs/celatone-frontend pull request #859
Opened 2024-03-30 07:20 UTC by Poafs1

Please refer to this ticket: https://linear.app/alleslabs/issue/CFE-403/[bug]-validator-details

2024-03-31 02:25 UTC, songwongtp reviewed
missing changelog

2024-03-31 02:25 UTC, songwongtp commented on src/lib/services/validator.ts
> +      .transform((items) => [...items].reverse()),
revert, let's change this in the api

2024-04-01 04:35 UTC, Poafs1 commented on src/lib/services/validator.ts
> +      .transform((items) => [...items].reverse()),
👍🏼

2024-04-01 10:15 UTC, evilpeach requested changes

2024-04-01 10:15 UTC, evilpeach commented on src/lib/pages/validator-details/components/bonded-token-changes/VotingPowerChart.tsx
> +
Move to outside

2024-04-02 04:07 UTC, songwongtp approved these changes

2024-04-02 07:21 UTC, evilpeach approved these changes

2024-04-02 09:20 UTC, evilpeach approved these changes

2024-04-02 09:20 UTC, merged