Fix(components): fix validator list/details bug bash
alleslabs/celatone-frontend pull request #877
Opened 2024-04-09 09:57 UTC by Poafs1

2024-04-10 07:23 UTC, evilpeach commented on src/lib/pages/validator-details/index.tsx
> +            <CustomTab onClick={handleTabChange(TabIndex.BondedTokenChanges)}>
Please rebase from the develop branch to update this code.

2024-04-10 07:54 UTC, songwongtp requested changes

2024-04-10 07:54 UTC, songwongtp commented on src/lib/components/table/proposals/ProposalTextCell.tsx
please revert this file and see `ProposalsTableMobileCard.tsx` as the template

2024-04-11 03:28 UTC, songwongtp requested changes

2024-04-11 03:28 UTC, songwongtp commented on src/lib/components/table/proposals/ProposalTextCell.tsx
> +const RenderMsg = ({ types }: { types: string[] }) =>
`types` on mobile and desktop are rendering differently. Please double check the original code

2024-04-11 04:02 UTC, songwongtp approved these changes

2024-04-11 09:19 UTC, evilpeach approved these changes

2024-04-11 09:21 UTC, merged