feat(components): adjust navigation and overview page for lite version
alleslabs/celatone-frontend pull request #898
Opened 2024-04-26 08:10 UTC by jennieramida

## Describe your changes

## Demo Link

2024-04-29 03:33 UTC, evilpeach commented on src/lib/layout/navbar/index.tsx
> +        ...(tier === "lite"
I suggest creating a separate file for lite tier insteads of adding condition here.

2024-04-29 03:35 UTC, evilpeach commented on src/lib/pages/home/lite.tsx
> +  const { data: overviewsStats, isLoading } = useOverviewsStats();
Add todo replace with latest block height data from lcd.

2024-04-30 07:48 UTC, evilpeach approved these changes

2024-04-30 09:12 UTC, Poafs1 commented on src/lib/layout/SubHeader.tsx
> +  const subMenu: SubHeaderMenuInfo[] =
Shall we make an objects for tier `full` and `lite` navigation bar separately. So it will be more easy to read?

2024-04-30 09:15 UTC, Poafs1 commented on src/lib/layout/SubHeader.tsx
> +            : []),
Can you make it as a function?

2024-04-30 09:17 UTC, Poafs1 commented on src/lib/layout/SubHeader.tsx
> +        ]
Actually, I think to make it more easy to read, no need to destruct the array. You can just `.flat()` at the end outer array to make the nested array flatten instead.

2024-04-30 09:20 UTC, Poafs1 commented on src/lib/layout/mobile/NavDrawer.tsx
> +// eslint-disable-next-line sonarjs/cognitive-complexity
I think if we separate a navbar objects, it should be fine. Can you test it. Thank!

2024-04-30 09:20 UTC, Poafs1 commented on src/lib/layout/mobile/NavDrawer.tsx
> -    {
Ditto

2024-04-30 09:21 UTC, Poafs1 commented on src/lib/layout/mobile/NavDrawer.tsx
> +        ];
Ditto, please update the navbar object according to the SubHeader.tsx above.

2024-04-30 09:30 UTC, Poafs1 commented on src/lib/layout/navbar/utils.ts
> +];
You can remove destructed array and use flatten instead. `.flat()`

2024-04-30 09:39 UTC, Poafs1 commented on src/lib/pages/home/components/QuickMenuLite.tsx
> +    ],
`.flat()`

2024-04-30 09:41 UTC, Poafs1 commented on src/lib/pages/home/components/QuickMenuMobileLite.tsx
> +  );
ditto

2024-04-30 09:44 UTC, Poafs1 commented on src/lib/pages/home/lite.tsx
> +        <section style={{ marginBottom: "48px", width: "100%" }}>
<Box as="section">
  ...
</Box>

2024-04-30 09:45 UTC, Poafs1 commented on src/lib/pages/home/full.tsx
> +      <section style={{ marginBottom: "48px" }}>
ditto

2024-04-30 09:46 UTC, Poafs1 commented on src/lib/pages/home/full.tsx
> +      <section>
ditto

2024-04-30 09:46 UTC, Poafs1 requested changes
:)

2024-05-09 04:02 UTC, Poafs1 approved these changes

2024-05-09 04:15 UTC, evilpeach approved these changes

2024-05-09 08:29 UTC, merged