[CFE-400]: Feature: add publish/republish tag to modules table
alleslabs/celatone-frontend pull request #902
Opened 2024-04-29 08:51 UTC by Poafs1

2024-04-30 04:06 UTC, songwongtp requested changes

2024-04-30 04:06 UTC, songwongtp commented on src/lib/components/table/modules/ModulesTableMobileCard.tsx
> +              <Box>
do we need `Box`?

2024-04-30 04:06 UTC, songwongtp commented on src/lib/components/table/modules/ModulesTableHeader.tsx
>      {!isPublishedModules && <TableHeader>Timestamp</TableHeader>}
combine

2024-04-30 04:06 UTC, songwongtp commented on src/lib/components/table/modules/ModulesTableRow.tsx
>              <Flex direction="column" gap={1}>
```
{!isPublishedModules && (
    <>
        <TableRow>....</TableRow>
        <TableRow>
            ...
            <Text ...>
                {moduleInfo.latestUpdated ? `(${dateFromNow(moduleInfo.latestUpdated)})` : "N/A"}
            </Text>
        </TableRow>
    </>
)}
```

2024-05-02 04:39 UTC, songwongtp commented on src/lib/components/table/modules/ModulesTable.tsx
> +          isRepublished={!!module.isRepublished}
remove use directly from `moduleInfo`

2024-05-02 04:40 UTC, songwongtp requested changes

2024-05-02 04:40 UTC, songwongtp commented on src/lib/components/table/modules/ModulesTableRow.tsx
> +        </TableRow>
ditto

2024-05-02 04:40 UTC, songwongtp commented on src/lib/components/table/modules/ModulesTableMobileCard.tsx
> +            </Flex>
not show in my published module

2024-05-02 05:36 UTC, songwongtp approved these changes

2024-05-02 05:37 UTC, evilpeach approved these changes

2024-05-02 05:38 UTC, merged