[CFE-483]: Feat(pages) - update my publish module to support lcd endpoint
alleslabs/celatone-frontend pull request #940
Opened 2024-05-24 06:50 UTC by Poafs1

2024-05-30 07:07 UTC, evilpeach commented on src/lib/services/move/module/index.ts
> +    if (!address) throw new Error("address is undefined");
`address is undefined (useModulesByAddressLcd)`

2024-05-30 07:10 UTC, evilpeach commented on src/lib/services/move/module/lcd.ts
> +      `${baseEndpoint}/initia/move/v1/accounts/${encodeURIComponent(address)}/modules/${encodeURIComponent(moduleName)}`
If address is string, I think it's okm to use `encodeURI`.

2024-06-04 06:42 UTC, songwongtp requested changes

2024-06-04 06:42 UTC, songwongtp commented on src/lib/pages/my-published-modules/components/MyPublishedModulesTable.tsx
> +  const liteData = useModulesByAddressLcd({
resApi, resLcd

2024-06-04 06:42 UTC, songwongtp commented on src/lib/services/move/module/index.ts
> +    [CELATONE_QUERY_KEYS.ACCOUNT_MODULES, lcdEndpoint, address],
CELATONE_QUERY_KEYS.MODULES_BY_ADDRESS_LCD

2024-06-05 06:32 UTC, evilpeach approved these changes

2024-06-05 08:07 UTC, songwongtp approved these changes

2024-06-06 04:16 UTC, merged