fix: asset input bug
alleslabs/celatone-frontend pull request #944
Opened 2024-05-27 16:10 UTC by evilpeach

- Can't select attach funds
- When adding more assets, a selected asset has gone.

2024-05-28 03:39 UTC, Poafs1 approved these changes
lgtm, can wait for @songwongtp to approve as well.

2024-05-28 08:07 UTC, songwongtp requested changes

2024-05-28 08:07 UTC, songwongtp commented on src/lib/components/fund/selectFund.tsx
capitalize filename

2024-05-28 08:07 UTC, songwongtp commented on src/lib/components/fund/selectFund.tsx
> -          initialSelected={field.denom}
not working

2024-06-19 03:01 UTC, Poafs1 approved these changes
lgtm

2024-06-19 07:55 UTC, evilpeach commented on src/lib/components/forms/SelectInput.tsx
> +  }, [initialSelected]);
Revert this. It's no need to remove options

2024-06-19 07:55 UTC, evilpeach commented on src/lib/components/fund/SelectFund.tsx
> +          initialSelected={field.denom}
revert this.

2024-06-19 09:39 UTC, songwongtp approved these changes

2024-06-19 09:48 UTC, merged