feat(components): adjust ui contract and account detail
alleslabs/celatone-frontend pull request #960
Opened 2024-06-07 04:39 UTC by jennieramida

## Describe your changes

fixes: CFE-502, CFE-503, CFE-504, CFE-505, CFE-506, CFE-506

## Demo Link

2024-06-18 07:48 UTC, songwongtp requested changes

2024-06-18 07:48 UTC, songwongtp commented on src/lib/components/state/AccountDetailEmptyState.tsx
> +export const AccountDetailEmptyState = ({
move to `account-details/components/` and rename both filename and the component name to `AccountDetailsEmptyState`

2024-06-18 07:48 UTC, songwongtp commented on src/lib/components/table/TableTitle.tsx
> +  helperText?: string | undefined;
remove `| undefined` already have `?`

2024-06-18 07:48 UTC, songwongtp commented on src/lib/pages/account-details/components/tables/txs/Full.tsx
> +    | undefined;
`transactions: Option<Transaction[]>`

2024-06-18 07:48 UTC, songwongtp commented on src/lib/pages/account-details/components/tables/txs/Full.tsx
> +              emptyState={getEmptyState({ transactions, selectedFilters })}
`getEmptyState({ transactions?.items, selectedFilters })`

2024-06-26 07:41 UTC, songwongtp approved these changes

2024-06-26 10:58 UTC, evilpeach approved these changes

2024-06-26 10:58 UTC, merged