Feat/new search
alleslabs/celatone-frontend pull request #992
Opened 2024-06-21 10:28 UTC by jennieramida

## Describe your changes

## Demo Link

2024-07-04 05:29 UTC, tansawit commented
small bug. most likely API level?

![CleanShot 2567-07-04 at 12 28 20@2x](https://github.com/alleslabs/celatone-frontend/assets/12265853/74ebb279-7707-4207-abfa-8e690c10ef86)

2024-07-15 03:56 UTC, Poafs1 commented on src/lib/layout/SearchResultRenderer.tsx
> +}) => {
Can you move this to interface pls.

2024-07-15 03:59 UTC, Poafs1 commented on src/lib/layout/SearchResultRenderer.tsx
> +}) => (
ditto

2024-07-15 04:00 UTC, Poafs1 approved these changes
lgtm. pls wait for Nat and Peach to review before merge

2024-07-17 09:05 UTC, evilpeach requested changes

2024-07-17 09:05 UTC, evilpeach commented on src/lib/layout/search/SearchComponent.tsx
> +  return (
Change to this

```ts
if (isMobile) return (<Button variant="outline-gray" size="sm" onClick={onOpen}>
          <CustomIcon name="search" boxSize={3} />
        </Button>)

return (<Flex>...</Flex>)
```

2024-07-17 09:05 UTC, evilpeach commented on src/lib/layout/search/SearchZeroState.tsx
> +  const starter = ["Account Address", "TX Hash", "Block Height"];
starter => base

2024-07-17 09:05 UTC, evilpeach commented on src/lib/layout/search/SearchZeroState.tsx
> +          <Flex alignItems="center" gap={3}>
Please add key.

2024-07-17 10:04 UTC, jennieramida commented on src/lib/layout/search/SearchComponent.tsx
> +  return (
can't, use same modal below

2024-07-17 10:09 UTC, songwongtp approved these changes

2024-07-17 10:09 UTC, songwongtp commented on src/lib/layout/search/SearchDisplayResult.tsx
> +export const SearchDisplayResult = ({
SearchResultItemBody

2024-07-17 10:29 UTC, evilpeach approved these changes

2024-07-17 10:30 UTC, Poafs1 approved these changes

2024-07-17 10:38 UTC, merged